### ISSUE TITLE
App wont build for ios

### ISSUE THREAD

**Issue by dinodsaurus** [katzer/cordova-plugin-email-composer#10]
It worked fine till yesterday but now when I try to build a project it says this:
The following build commands failed:
    CompileC build/eSmPC2.build/Debug-iphonesimulator/eSmPC2.build/Objects-normal/i386/CDVFile.o eSmPC2/Plugins/org.apache.cordova.file/CDVFile.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC build/eSmPC2.build/Debug-iphonesimulator/eSmPC2.build/Objects-normal/i386/CDVFileTransfer.o eSmPC2/Plugins/org.apache.cordova.file-transfer/CDVFileTransfer.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)

```
at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cordova/src/compile.js:65:22)
at ChildProcess.EventEmitter.emit (events.js:98:17)
at maybeClose (child_process.js:735:16)
at Process.ChildProcess._handle.onexit (child_process.js:802:5)
```

The only difference is that I changed provisioning profile. when I remove this plugin build passes.

**Comment by ulrick** [comment]
Hello! 
I have the same error but the plugin is well installed!! may I remove platform, add, prepare and rebuild?
I think the problem is in my config.xml when adding "<gap:plugin name="cordova-plugin-email-composer" version="0.8.3" source="npm" />"
Help please!

**Comment by ulrick** [comment]
I removed and reinstalled the plugin and the problem is solved.

Thnks!
