### ISSUE TITLE
How to check if email is sent (callback is called if send or cancelled)?

### ISSUE THREAD

**Issue by softBarbarian** [katzer/cordova-plugin-email-composer#100]
Hello, is there a way to check if email is sent (callback is called if send or cancelled)?

**Comment by krik** [comment]
Is it possible to do? I'd be willing get into native dev for this. :p

**Comment by zapnap** [comment]
Seems like there's no way to check if the external intent sent the mail or cancelled, correct?

**Comment by PKnittel** [comment]
Yes. Android don´t serve any kind of Email-Intent wich allow to check that information.
So we decided to not implement this feature cause of cross-platform-consistency.
