### ISSUE TITLE
Causes Gmail to quit unexpectedly when attaching PNG to email.

### ISSUE THREAD

**Issue by tyler-markvluwer** [katzer/cordova-plugin-email-composer#101]
When testing on Android 4.4.2, the plugin causes Gmail to quit unexpectedly. Email service picker opens, I choose gmail, all of the info is there including the file that I have attached, but 5-10 seconds later it closes. Upon re-opening it will simply reclose until I force quit Gmail.

**Comment by PKnittel** [comment]
I tested it on android 4.2 and 4.4 and it worked with .png files. Maybe your attached file is to large. Check the Example branch for information about how to attach files correctly.
