### ISSUE TITLE
Windows.ApplicationModel.Email not available on Windows Store universal apps

### ISSUE THREAD

**Issue by jellehermsen** [katzer/cordova-plugin-email-composer#103]
I tried to use this plugin on a Windows Store app (not Windows Phone), but since Windows.ApplicationModel.Email is not available, this plugin does not work. Maybe it's a good idea to check for its existence in the isAvailable function?

I'm personally looking into using the Windows.ApplicationModel.DataTransfer "share" functionality to get attachment e-mailing working.

**Comment by amrigaye** [comment]
Hello, i have the same matter! Need to use Windows.ApplicationModel.Email namespace for sendind email with attachment on a windows 8.1 app but the  visual studio don't found it! Is someone find the way to do that please?

**Comment by iqmeta** [comment]
Same here...
for now workaround...
```javascript
if (cordova.platformId == "windows") {
            var mailto = new Windows.Foundation.Uri("mailto:?" +
                "to=my.address@here.com" +
                "&cc=cc@here.com" +
                "&bcc=bcc@here.com" +
                "&subject=test" +
                "&body=" + escape('Hello,\nHow are you?\nwhat') + "");
            Windows.System.Launcher.launchUriAsync(mailto);
        }
        else {
            cordova.plugins.email.open({
                to: 'max@mustermann.de',
                cc: 'erika@mustermann.de',
                bcc: ['john@doe.com', 'jane@doe.com'],
                subject: 'Greetings',
                body: 'How are you? Nice greetings from Leipzig'
            });
        }
```

**Comment by PKnittel** [comment]
Currently the plugin only supports the WP8.1 part of the windows platform. We plan to add the desktop part with our next release. Using mailto is an option, but it don´t support atachments.
