### ISSUE TITLE
Carriage returns being removed from Body of email.

### ISSUE THREAD

**Issue by aherold** [katzer/cordova-plugin-email-composer#104]
I just updated from 0.8.1 to 0.8.2 for Lollipop support. Looks good except that I've lost new lines in the body of messages. So a message that should read:

Dear Joe,
This is easy to read.
Thanks

Is now:
Dear Joe, This is easy to read. Thanks

Breaks a critical feature for my app, and need L support asap.
I have not made any code changes, just this update. The issue is also occurring with Android 4.4.2 with this update, so I'm thinking it's not OS or mail app related. Any ideas?

**Comment by PKnittel** [comment]
'Dear Joe, <br> This is easy to read. <br> Thanks' Should work on android.

Hope that helps you.
