### ISSUE TITLE
draft = [[MFMailComposeViewController alloc] init] 

### ISSUE THREAD

**Issue by mobilabgit** [katzer/cordova-plugin-email-composer#107]
When we install the app for the first time and then try to e-mail we sometimes see the app crashing on this line: draft = [[MFMailComposeViewController alloc] init];

This is what the debugger shows:

 -[__NSCFString _recordInvocation:withClassName:containerClassNames:selectorString:forRemoteProcess:]: unrecognized selector sent to instance 0x170250920
2015-04-21 13:36:09.824 Declareren[1514:8dc7] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString _recordInvocation:withClassName:containerClassNames:selectorString:forRemoteProcess:]: unrecognized selector sent to instance 0x170250920'

**Comment by PKnittel** [comment]
Could you describe the issue a bit more detailed, please?

**Comment by mobilabgit** [comment]
It seemed to be related to a click event in our app that fires twice almost simultaneously (the well known ghost click in hybride apps). The second event causes the exception. I just placed a try catch block around this code to prevent the error from disrupting my app flow.
