### ISSUE TITLE
iOS 8.3 - Adding Email Addresses Crash

### ISSUE THREAD

**Issue by jmays86** [katzer/cordova-plugin-email-composer#108]
Hi,

When adding an email address using the email composer, if I select my own address from 'recent' in the drop down, the email composer window closes and takes me back to the app.

It seems to be a little random and rarely happens on any other addresses. Only once did it happen on a different address other than my own. Not sure if this is co-incidence.

Seems to only effect 8.3 as I have tested earlier versions without problem.

Thanks

**Comment by gblotter** [comment]
Experienced the same thing this morning

**Comment by PKnittel** [comment]
Could you describe the Issue a bit more detailed?
