### ISSUE TITLE
Including <img> tag in the body

### ISSUE THREAD

**Issue by omeszar** [katzer/cordova-plugin-email-composer#11]
Is it possible to include an image tag in the body.

I have something like:
window.plugin.email.open({
body: "&lt;img src='http://validimage.com/image.jpg' /&gt;&lt;br /&gt;&lt;a href='http://github.com' &gt;here&lt;/a&gt;",
isHtml: true
});

The link is created properly, but instead of getting the image, even though I checked the URL to make sure it is valid, it displays an [obj] tag.

I'm trying this on a Android device. At this moment I don't know if the problem is with the plug in or with the mobile device itself.

Thanks

**Comment by alemartel** [comment]
@omeszar  @katzer any solution for this issue??

**Comment by samimaliks** [comment]
facing same issue.. it display only obj.. though I have base64 encoded image
