### ISSUE TITLE
cordova is not defined: version 0.8.2 doesn't work 

### ISSUE THREAD

**Issue by andreamontanari** [katzer/cordova-plugin-email-composer#114]
Hi,

I installed the latest module of cordovaEmailComposer (0.8.2) that added the name space: cordova.plugins.email.
When I try to use it, following your tutorials, I get the error on file ng-cordova.js at this point:
cordova.plugins.email.isAvailable(function (isAvailable) 
saying that "cordova is not defined".

Any suggestion?

**Comment by PKnittel** [comment]
This error should have nothing to do with the plugin. For an easy way to get started using our plugin, just download the example app inside the example branch. Hope that will help you.
