### ISSUE TITLE
Is it possible to send an email without confirmation?

### ISSUE THREAD

**Issue by khuongduybui** [katzer/cordova-plugin-email-composer#116]
I'm writing an unattended-responding app. I need the app to be able to send emails upon certain events without user interactivity.

**Comment by PKnittel** [comment]
Thats not possible with the email-composer-plugin. There are different librarys (like BackgroundMailLibrary) for both, android and ios to support that feature, but in this case you have to save the connection-data, usernames and passwords inside of your application.
