### ISSUE TITLE
Question:  Email is available but not setup condition

### ISSUE THREAD

**Issue by randallbpotter15** [katzer/cordova-plugin-email-composer#117]
User is using application that can "email" - but the user has not setup any email accounts on the device.  This could be either android or iPhone but in particular iPhone I would imagine.

Is there a way to check this condition and respond appropriately?

IOS:
http://stackoverflow.com/questions/4522740/check-if-user-has-email-set-up-on-their-idevice

Android:  Not checked answer, but second answer where the user says they implemented it a certain way.  Direct link to answer:  http://stackoverflow.com/a/15679615

**Comment by katzer** [comment]
Thanks
