### ISSUE TITLE
Only show email apps in chooser on Android

### ISSUE THREAD

**Issue by symbiat** [katzer/cordova-plugin-email-composer#118]
Just wondering why you do use `ACTION_SEND_MULTIPLE` instead of `ACTION_SENDTO` when firing the Intent. User expects to be able to select their default email app but right now that Intent gives you a list which includes things like Android Beam, Skype, Google Drive, etc. which might be confusing to users. Or allow specifying a list of apps to use to send email instead of just one. While we could specify that only the Gmail app be used, I think this is not good because there will be Android devices out there that dont have Gmail and Android is about allowing the user to choose anyway. There needs to be a middle ground where we let the user use amongst only email-capable apps.

See related SO discussion: http://stackoverflow.com/questions/8701634/send-email-intent

**Comment by anvaka** [comment]
Just discovered this behavior as well: Android offers skype, while I expect only email clients.

@katzer what do you think about suggested fix?

**Comment by katzer** [comment]
@anvaka I will look into it. I am working on a new release within the next days

**Comment by anvaka** [comment]
Awesome! Thank you!

**Comment by katzer** [comment]
@symbiat, @anvaka  - The reason for using `ACTION_SEND_MULTIPLE` is to indicate that you want to send multiple attachments. You can see [here](https://developer.android.com/guide/components/intents-common.html#Email) for more infos.

I've made the change that when having no attachments the chooser will only display email clients. But with attachments the chooser - as before - will display all apps who can receive attached files.
