### ISSUE TITLE
isAvailable() returns false on Android 5

### ISSUE THREAD

**Issue by tellibus** [katzer/cordova-plugin-email-composer#119]
Thank you for the plugin!
Am I wrong, or a recent commit introduced some kind of regression: when checking out to current version, isAvailable() returns always false now, and when checking out specifically to #0.8.2 it works again.
Only tested on one (Samsung) device on Android 5.0.1 with both stock email and Gmail setup. If that matters, multiple accounts are setup on both stock email app and Gmail...

**Comment by katzer** [comment]
@tellibus I think its already fixed in the meantime. I am working on a recent update and the dev version works on Android 5 & 6. Just give it a try.
