### ISSUE TITLE
Anyway to check if chooser has been shown?

### ISSUE THREAD

**Issue by RonCan** [katzer/cordova-plugin-email-composer#120]
I'm attaching a pdf file in email which is constructed using pdfmake. Now I Am using the loading icon which is dismissed AFTER the pdf has been constructed but between the loading icon being dismissed and the chooser appearing there is a considerably long gap(perhaps it uploads before showing the chooser because as soon as the chooser is shown and Gmail is clicked the file has already been uploaded). That gap is very frustrating, am I doing something wrong? is there a way I can dismiss loading icon only after the chooser has been show?

**Comment by katzer** [comment]
I hope you found a way in the meantime. The plugin itself uses threads to not block the main app.
