### ISSUE TITLE
App Crashes in iOS with EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by olivermpo** [katzer/cordova-plugin-email-composer#122]
Hi

I upgraded to the latest version a few days ago, and whenever I try to open mail in iOS it crashes and I get NSString* res = [webView stringByEvaluatingJavaScriptFromString:jsCall]; EXC_BAD_ACCESS on this line(557) in the CDDVViewController.m  shouldAutorotateToInterfaceOrientation function.

I also downloaded the example and ran that to make sure that the issue is not with my application, and I get the same thing.

Interestingly both work fine if I run in the IOS simulator.

Any advice?

**Comment by ocomsoft** [comment]
I am seeing the same issue at the same line of code. 

IOS 8.13 (12B466)

**Comment by whyameye** [comment]
@olivermpo what version did you use before you had this error? I am getting the same error (iOS 8.4) and will revert back to the older version as a workaround for now.

**Comment by whyameye** [comment]
this crash seems to go away for me if iOS email is configured. Related: isAvailable() also crashes if iOS email is not configured, but returns "true" as it should if email is configured.

**Comment by ocomsoft** [comment]
I was testing on a New IPhone that didnt have mail configured.  So that could be the reason I am getting the same error.  I cannot confirm for a few days.

**Comment by olivermpo** [comment]
Hi
I tested with 8.3 and 8.4. Same result

**Comment by dseravalli** [comment]
I am getting this too on 8.4.1. isAvailable returns true.

**Comment by drjimmie1976** [comment]
Can confirm the behaviour only happens when email is not configured on iOS, works fine if an account is set up.

**Comment by katzer** [comment]
It has been fixed. Thanks!
