### ISSUE TITLE
Compiling for android

### ISSUE THREAD

**Issue by any2info** [katzer/cordova-plugin-email-composer#126]
Is it possible to use this plugin with visual studio's Tools for apache corova?

When trying to build the example application i found that building for ios works fine. 
When i try to build the plugin for android, my compilers throws the following error:
"no suitable constructor found for PluginResult(Status, List<PluginResult>)'

Does anybody know what i'm forgetting?

**Comment by dancj** [comment]
I'm seeing the same error when compiling for Android after just installing this plugin.

/platforms/android/src/de/appplant/cordova/emailcomposer/EmailComposer.java:117: error: no suitable constructor found for PluginResult(Status,List<PluginResult>)

How did you solve it?

**Comment by grecor** [comment]
I'm seeing the same compile time error:

/src/de/appplant/cordova/emailcomposer/EmailComposer.java:117: error: no suitable constructor found for PluginResult(Status,List<PluginResult>)

 I'm using cordova cli 4.1.2
