### ISSUE TITLE
Plugin throws "Not Implemented" on platform windows

### ISSUE THREAD

**Issue by inhji** [katzer/cordova-plugin-email-composer#127]
I'm using version 0.8.2  of the plugin. I'm testing on a real device, a Lumia 630 with OS-Version `8.10.14234.375`

When I'm calling the open method like this:

```
var EmailComposer = cordova.plugins.email;
var options = {
  subject: "my subject",
  body: "my body",
  to: ["email@address.com"],
  attachments: ["file:///C:/Data/Users/DefApps/APPDATA/Local/Packages/DigitalData.SimpleCapture_bzbj8h50hftv4/LocalState/Bilder/QA-jjhh.jpg"]
EmailComposer.open(options);
```

the plugin throws a **"Not Implemented"** exception and then crashes the app. As far as I can see the error occurs when the `showComposeNewEmailAsync` method is called.

~~I'm not sure if this is really a bug, maybe my filename is in the wrong format, if so, can you give me an example how the filename should look like?~~

EDIT: I did some more testing and the problem is definitely the attachment. The Exception only is thrown when I specify the `attachments` option. Which format should the filename/fileuri be?

**Comment by inhji** [comment]
Ok, I bypassed the issue by encoding my files with base64 and passing that to `attachments`.

**Comment by Jcbobo88** [comment]
sorry  i'm becoming crazy on the same think on a  lumia 635 with os version 8.10.14219.341
there is my code
report={};
report.name='report_name'
report.file='content'
window.cordova.plugins.email.open({
                            to:      email,
                            attachments:['base64:'+report.name+'.txt//'+base64.encode(report.file)],
                            subject: 'Scheda relazione cliente '+report.name,
                            body:    'invio file per importazione '
                        });

the mail client is opened but without attachment
