### ISSUE TITLE
App crashes when trying to open email composer without any accounts set up

### ISSUE THREAD

**Issue by locnguyen** [katzer/cordova-plugin-email-composer#131]
This is probably super edge case but I just got a new iPhone 6+ (8.4.1). I am testing my app on it and when I try to open the composer with this plugin the app crashes. After adding one email account then all is well.

**Comment by jnis77diver** [comment]
We are having the exact same issue. I was testing on an iPhone 4S without any email account setup and our app crashed. When i set up email account, it worked fine.

**Comment by TylerAldrich** [comment]
@locnguyen @jnis77diver You can check out the diff in this open PR to see how I fixed this issue https://github.com/katzer/cordova-plugin-email-composer/pull/130

I'm running a script every time I build that redownloads plugins and patches the file.

**Comment by jnis77diver** [comment]
@TylerAldrich Thanks much. We are not in a big hurry so hopefully your PR will get merged in before we need to go to production on this app.

**Comment by jnis77diver** [comment]
@katzer, is there any plan to merge in @TylerAldrich 's PR? Seems like a quick fix. Thx

**Comment by ocomsoft** [comment]
+1

**Comment by Hirbod** [comment]
+2

**Comment by cmeredith** [comment]
+3

**Comment by mnewmedia** [comment]
+4

**Comment by Hirbod** [comment]
rewind - +6

**Comment by Hirbod** [comment]
#130 already fixed this problem... Just one "merge" click away. But looks like this repo is dead.

**Comment by raphaelseher** [comment]
FYI: Apple Review Team is testing the apps with no accounts set up. So you will get rejected, because your app crashes, when trying to send an Email.

**Comment by katzer** [comment]
Has been fixed!
