### ISSUE TITLE
Html anchors (<a href="..") only works on gmail

### ISSUE THREAD

**Issue by PedroJusto** [katzer/cordova-plugin-email-composer#132]
on Samsung email app links are not clickable, they are shown as plain text :

cordova.plugins.email.open({
   ...
   body: '<[anchor] href="http://www.google.pt">google website</[anchor]>',
   isHtml: true
});

'[anchor]' should be replaced by 'a' in code

**Comment by regnete** [comment]
We reproduce the same effect using the preinstalled Samsung E-Mail App.
Hardware: GT-N8000 (Samsung Galaxy Note)
OS: Android 4.4.2 

I guess this is due to limitations of the E-Mail-App, not the plugin.

**Comment by katzer** [comment]
```
I guess this is due to limitations of the E-Mail-App, not the plugin.
```

Thats true and even Gmail HTML/CSS support is limited.
