### ISSUE TITLE
Carriage Returns + "\n" are not detected in some cases on iOS

### ISSUE THREAD

**Issue by amihaylo** [katzer/cordova-plugin-email-composer#133]
When sending from an email client on my android to a work email, the format is perfect. However when I run the exact same app from my apple device and send an email, some newlines are not displayed which is a big problem since the emails are parsed after.

EDIT: I have further simplified the problem after some lengthy testing and I am stunned at the chaotic behaviour of this. Here is what I have determined. For a string of **length 40** that has a space **after the 6th** character, the newline is neglected for some reason.  Here is the code

    $("#testButton2").click(function(){
	var emailBody = "";
	emailBody += "test line1" + "<br/>";
	emailBody += "tttttt ttttttttttttttttttttttttttttttttt" + "<br/>";
	emailBody += "test line2" + "<br/>";
	cordova.plugins.email.open({
	    to:      'example@gmail.com', 	  
	    subject: 'Greetings',
	    body:     emailBody,
	    isHTML: true
	});
    });

This will cause the following output:

    test line1
    tttttt ttttttttttttttttttttttttttttttttt test line2

**Note** that for some strange reason only occurs if the receiving email is opened in outlook (works on gmail)

The whole thing is so bizarre and is turning out to be a big headache.

**Comment by pallaviMN** [comment]
@amihaylo , can you please let me know how did u fix this, because i am facing the same issue in android outlook
