### ISSUE TITLE
Getting Error at PluginResult result = new PluginResult(PluginResult.Status.OK,messages)

### ISSUE THREAD

**Issue by mallikarjunaj** [katzer/cordova-plugin-email-composer#139]
Getting Error at PluginResult result = new PluginResult(PluginResult.Status.OK,messages) in Android isAvailable() function.
Error is "Cannot resolve constructor"

**Comment by gmarziou** [comment]
Try installing 0.8.2

cordova plugin add de.appplant.cordova.plugin.email-composer@0.8.2

**Comment by katzer** [comment]
@mallikarjunaj See latest version - Build runs without failures

**Comment by mallikarjunaj** [comment]
Thanks




Regards,
---------------------------
Mallikarjuna J

On Tue, Feb 23, 2016 at 11:49 AM, Sebastián Katzer <notifications@github.com
