### ISSUE TITLE
Error of undefined object on serRecipients function ( EmailComposerProxyImpl.js )

### ISSUE THREAD

**Issue by Pavel-Durov** [katzer/cordova-plugin-email-composer#140]
I am using this plugin on Windows Phone as Universal App (cordova.platformId == "windows").

When I am trying to call  utils.sendMail from my cordova app on Windows Phone Universal I got this error:

module emailcomposer.EmailComposer not found

Stack trace:

"TypeError: Unable to get property 'push' of undefined or null reference\n   
 Anonymous function (ms-appx://com.qmarkets.qmarketstouch/www/plugins/de.appplant.cordova.plugin.email-composer/src/windows/EmailComposerProxyImpl.js:123:17)\n   
 setRecipients (ms-appx://com.qmarkets.qmarketstouch/www/plugins/de.appplant.cordova.plugin.email-composer/src/windows/EmailComposerProxyImpl.js:121:9)\n   
 getDraftWithProperties (ms-appx://com.qmarkets.qmarketstouch/www/plugins/de.appplant.cordova.plugin.email-composer/src/windows/EmailComposerProxyImpl.js:42:9)\n   
 open (ms-appx://com.qmarkets.qmarketstouch/www/plugins/de.appplant.cordova.plugin.email-composer/src/windows/EmailComposerProxy.js:52:9)\n   
 exports (ms-appx://com.qmarkets.qmarketstouch/www/cordova.js:901:13)\n   
 onAvailable (ms-appx://com.qmarkets.qmarketstouch/www/plugins/de.appplant.cordova.plugin.email-composer/www/email_composer.js:98:13)\n   
 callbackFromN
ive (ms-appx://com.qmarkets.qmarketstouch/www/cordova.js:291:41)\n   
 callbackSuccess (ms-appx://com.qmarkets.qmarketstouch/www/cordova.js:271:9)\n   
 onSuccess (ms-appx://com.qmarkets.qmarketstouch/www/cordova.js:874:17)\n   
 isAvailable (ms-appx://com.qmarkets.qmarketstouch/www/plugins/de.appplant.cordova.plugin.email-composer/src/windows/EmailComposerProxy.js:35:5)"
 
 
 The issue here ( draft is undefined ):
 

 setRecipients: function (recipients, draftAttribute) {
        recipients.forEach(function (address) {
                draft.push(
                    new Windows.ApplicationModel.Email.EmailRecipient(address));
        });
    }
	
I've overcame this issue by injecting draft to proxy.draftUtil  on setSubject...

setRecipients: function (recipients, draftAttribute) {
        recipients.forEach(function (address) {
            if (this.draft) {
                this.draft.push(
                    new Windows.ApplicationModel.Email.EmailRecipient(address));
            }
        });
    },
 I've got
When I am trying to call  utils.sendMail from my cordova app on Windows Phone Universal I got this error:

module emailcomposer.EmailComposer not found

This is the stack trace:

"TypeError: Unable to get property 'push' of undefined or null reference\n   
 Anonymous function (ms-appx://com.qmarkets.qmarketstouch/www/plugins/de.appplant.cordova.plugin.email-composer/src/windows/EmailComposerProxyImpl.js:123:17)\n   
 setRecipients (ms-appx://com.qmarkets.qmarketstouch/www/plugins/de.appplant.cordova.plugin.email-composer/src/windows/EmailComposerProxyImpl.js:121:9)\n   
 getDraftWithProperties (ms-appx://com.qmarkets.qmarketstouch/www/plugins/de.appplant.cordova.plugin.email-composer/src/windows/EmailComposerProxyImpl.js:42:9)\n   
 open (ms-appx://com.qmarkets.qmarketstouch/www/plugins/de.appplant.cordova.plugin.email-composer/src/windows/EmailComposerProxy.js:52:9)\n   
 exports (ms-appx://com.qmarkets.qmarketstouch/www/cordova.js:901:13)\n   
 onAvailable (ms-appx://com.qmarkets.qmarketstouch/www/plugins/de.appplant.cordova.plugin.email-composer/www/email_composer.js:98:13)\n   
 callbackFromN
ive (ms-appx://com.qmarkets.qmarketstouch/www/cordova.js:291:41)\n   
 callbackSuccess (ms-appx://com.qmarkets.qmarketstouch/www/cordova.js:271:9)\n   
 onSuccess (ms-appx://com.qmarkets.qmarketstouch/www/cordova.js:874:17)\n   
 isAvailable (ms-appx://com.qmarkets.qmarketstouch/www/plugins/de.appplant.cordova.plugin.email-composer/src/windows/EmailComposerProxy.js:35:5)"
 
 
 The issue here ( draft is undefined ):
 

 setRecipients: function (recipients, draftAttribute) {
        recipients.forEach(function (address) {
            
                draft.push(
                    new Windows.ApplicationModel.Email.EmailRecipient(address));
            
        });
    },
	
I've overcame this issue with injecting draft to proxy.draftUtil  on setSubject...

so thats what I've got

setRecipients: function (recipients, draftAttribute) {
        recipients.forEach(function (address) {
            if (this.draft) {
                this.draft.push(
                    new Windows.ApplicationModel.Email.EmailRecipient(address));
            }
        });
    }

**Comment by gabrielgt** [comment]
Hello, 

I had the same problem but I solved it just changing draftAttribute for draft in setRecipients function. I tried your code first, and it didn't work for me, the to field remains empty.

BR

**Comment by Pavel-Durov** [comment]
OK, thanks

**Comment by jdnichollsc** [comment]
+1

**Comment by jdnichollsc** [comment]
See more detail please => http://screencast.com/t/CcsVXIkDT9

**Comment by katzer** [comment]
@Pavel-Durov Has been fixed
