### ISSUE TITLE
'Cordova/NSData+Base64.h' file not found

### ISSUE THREAD

**Issue by didi3r** [katzer/cordova-plugin-email-composer#141]
During compiling for iOS platform, the following error occurs:

.../Plugins/de.appplant.cordova.plugin.email-composer/APPEmailComposer.m:24:9: fatal error: 
      'Cordova/NSData+Base64.h' file not found
#import "Cordova/NSData+Base64.h"
        ^
1 error generated.

I'm using Cordova 5.3.3 and the last version of the plugin downloaded from this git repo.

**Comment by hypery2k** [comment]
you can use my plugin: https://www.npmjs.com/package/cordova-plugin-email

It's updated to support cordova ios 4

**Comment by katzer** [comment]
@didi3r Has been fixed.

**Comment by Ramprasathselvam** [comment]
Refer this Link
https://stackoverflow.com/questions/36348202/cordova-4-0-1-cdv-camera-cordova-nsdatabase64-h-not-found/52606879#52606879
