### ISSUE TITLE
IOS 9 canOpenURL error

### ISSUE THREAD

**Issue by briand617** [katzer/cordova-plugin-email-composer#142]
This error is reported in detail on Stackexchange here: http://stackoverflow.com/questions/32984304/cordova-ionic-email-plugin-not-working-on-ios-9-due-to-url

IOS 9 only shows this error when trying to create an email: -canOpenURL: failed for URL: "mailto:test@test.de"

It is apparently related to some change with IOS 9 where you need to provide an exception in the plist file like this:

&lt;key&gt;LSApplicationQueriesSchemes&lt;/key&gt;
  &lt;array&gt;
    &lt;string>mailto&lt;/string&gt;
  &lt;/array&gt;

But this doesn't solve the problem either.

Plugin works fine in IOS 8.  I am using latest production Cordova and plugin version 0.8.2

**Comment by rajild** [comment]
+1

**Comment by piermariacosina** [comment]
+ 1

**Comment by mnewmedia** [comment]
+1

**Comment by rqroz** [comment]
+1

**Comment by scenekidsanta** [comment]
+1

**Comment by shankari** [comment]
0
down vote
	

I can confirm that when the stock plugin (no LSApplicationQueriesSchemes) is installed on an actual device with the mail client configured, it works great.

I think that canOpenURL issues primarily occur on the simulator and even if you magically resolve them, a simulator with version > 8 will generate a native crash.
Note this code:
https://github.com/katzer/cordova-plugin-email-composer/blob/master/src/ios/APPEmailComposer.m#L182

And even on the actual device, if you don't set up the default mail client, then you get all kinds of weird crashes (controller is not displayed in UI view, etc).

Just try it on a device with the mail client configured and your life will be easy.

**Comment by mnewmedia** [comment]
whatever, making life easy is using a maintained repo..
https://github.com/hypery2k/cordova-email-plugin

**Comment by shankari** [comment]
@mnewmedia, I am definitely open to using a repo that has more fixes. But I looked at the commit history on repo, and the only substantial, non-packaging changes that I see are:
- return an isSent() callback on iOS only
- change `isAvailable` to have an errorCallback that always returns `false`

Have you actually fixed this to work on the simulator? If so, can you point me to the checkin with the fix?
