### ISSUE TITLE
Add to npm

### ISSUE THREAD

**Issue by mobidev111** [katzer/cordova-plugin-email-composer#144]
See this fork: https://github.com/hypery2k/cordova-email-plugin/commit/b37ac5fb99105e299b59d36f1bdc69ed8c474ac9

**Comment by mnewmedia** [comment]
+1

**Comment by sebastien-p** [comment]
Please do, plugins.cordova.io isn't a thing anymore so the only way to get this plugin to work on PhoneGap Build is to add the package to npm.

**Comment by CheetahDev** [comment]
+1

**Comment by KillerCodeMonkey** [comment]
@mobidev111 @mnewmedia @sebastien-p @CheetahDev 

I added the plugin to npm
https://github.com/KillerCodeMonkey/cordova-plugin-email-composer

https://www.npmjs.com/package/cordova-plugin-email-composer
cordova-plugin-email-composer

If somebody will contribute --> feel free.

Because i get the error "could not attach file" on Android devices with current cordova CLI

**Comment by mnewmedia** [comment]
there are some forks around, but having 1 version somewhere where pull requests are getting merged and all others would know which fork to go, would be nice.

**Comment by mobidev111** [comment]
agree. I would rather have the original maintainer add the project to NPM - handing the release process over to two different parties most likely brings inconsistencies

**Comment by mobidev111** [comment]
and worse: the forks "take away" download count and thus get popularity while being outdated.

**Comment by mobidev111** [comment]
@katzer @PKnittel any update guys?

**Comment by KillerCodeMonkey** [comment]
yes indeed,

but we need a really fast fix for that and so on.
i would accept pull request really fast, because i trust in the contributers.
So if somebody has something to get in there --> the time is right.

Does everyone noticed something similar on android?

**Comment by mnewmedia** [comment]
Thank for adding to NPM @PKnittel but are you planning to maintain this plugin a little bit in the future? Or should the community define a fork as the new to go version?

Cause this is right now, very buggy and there are some pull requests open..

**Comment by regnete** [comment]
Oh yes. The plugin is very usefull but needs some enhancements and fixes.

I will e.g. provide a pull request regarding windows support within the next weeks. Even html emails will then be supported with outlook as email client.

Shall we fork or proceed with this repo?


Felix Schauerte
sitewaerts GmbH
www.sitewaerts.de<http://www.sitewaerts.de>

Am 25.11.2015 um 11:39 schrieb mnewmedia <notifications@github.com<mailto:notifications@github.com>>:


Thank for adding to NPM @PKnittel<https://github.com/PKnittel> but are you planning to maintain this plugin a little bit in the future? Or should the community define a fork as the new to go version?

Cause this is right now, very buggy and there are some pull requests open..

-

**Comment by mnewmedia** [comment]
Because of the problem which fork to go: I will go https://github.com/hypery2k/cordova-email-plugin because he is very active and is updated already for ios 4!

**Comment by katzer** [comment]
The repo is still maintained, it sometimes takes a while but an update and npm is on the way.
