### ISSUE TITLE
Feel really stupid, but...

### ISSUE THREAD

**Issue by Fuchur84** [katzer/cordova-plugin-email-composer#148]
Hi... 
I feel rather stupid right now but I just can't get this plugin to run. 
(I am using the phonegap desktop app 0.1.11 but I think this should not make any difference)

1.) I have used phonegap-CLI to add it to my project like this:
`phonegap cordova plugin add cordova-plugin-email`.
2.) The folder "/plugins/cordova-plugin-email" gets created and it tells me everything is fine.
3.) When I open my app and do this: 
`var plugins = cordova.require("cordova/plugin_list").metadata;`
`console.log(plugins);`

I use weinre to debug it and I get this then: 
`ADBMobile: "1.0.0"`
`com.megster.cordova.ble: "0.1.9"`
`cordova-plugin-battery-status: "1.0.0"`
`cordova-plugin-camera: "1.0.0"`
`cordova-plugin-console: "1.0.1"`
`cordova-plugin-contacts: "1.0.0"`
`cordova-plugin-device: "1.0.1"`
`cordova-plugin-device-motion: "1.0.0"`
`cordova-plugin-device-orientation: "1.0.1"`
`cordova-plugin-dialogs: "1.0.0"`
`cordova-plugin-file: "3.0.0"`
`cordova-plugin-file-transfer: "1.0.0"`
`cordova-plugin-geolocation: "1.0.1"`
`cordova-plugin-globalization: "1.0.1"`
`cordova-plugin-inappbrowser: "1.0.1"`
`cordova-plugin-media: "1.0.1"`
`cordova-plugin-media-capture: "1.0.1"`
`cordova-plugin-splashscreen: "2.1.0"`
`cordova-plugin-statusbar: "1.0.1"`
`cordova-plugin-vibration: "1.0.0"`
`cordova-plugin-whitelist: "1.0.0"`
`nl.x-services.plugins.insomnia: "4.0.1"`
`phonegap-plugin-contentsync: "1.1.12"``

As you can see, there is no email-plugin available here. 
I can not use cordova.plugins.email.isAvailable neighter. 
(it just does not know this, as it seems.)

The File or FileTransfer-Plugin worked as it should and I can use it but the syntax there is  a little different so just to test everything I could I tried to do it this way, which is the way it works with File and FileTransfer (I doubt it would work that way, since these are base-plugins, but who knows?):
`var eMail = new EmailComposer();`
`eMail.isAvailable(function (isAvailable) {...});`
But this did not work neighter.

4.) Okay so I tried using the other, deprecated namespace 
`window.plugin.email.isAvailable(function (isAvailable) {...});` 
but this did not work neighter.

5.) So I added a built-target to see what is happening in the platforms/android-folders.
(I did a remove and add-cli-command to be sure that this did not do anything.

6.) I then read about "prepare" and did that too like this:
`phonegap cordova plugin prepare` and just to be sure `phonegap cordova prepare` 
(I think both do the same, but I am not sure about that)

7.) After that I had a look into the file "platforms/android/assets/wwww/cordova_plugins.js":
At the bottom there is an entry like this
`{`
`        "file": "plugins/cordova-plugin-email/www/email_composer.js",`
`        "id": "cordova-plugin-email.EmailComposer",`
`        "clobbers": [`
`            "cordova.plugins.email",`
`            "plugin.email"`
`        ]`
`    }`
> looks okay, if I compare it to the other entry... only the filename has that underscore in it, but I think that should be okay, right? At least under "plugins/cordova-plugin-email/www/email_composer.js" the file is available.

8.) Then I had a look at "platforms/android/res/xml/config.xml". There is an entry like this:
`    <feature name="EmailComposer">`
`        <param name="android-package" value="de.martinreinhardt.cordova.plugins.email.EmailComposer" />`
`    </feature>`

9.) Just to be sure I ran this to see, if the plugin is recognized by phonegap correctly:
`phonegap cordova plugin` 
`cordova-plugin-console 1.0.0 "EmailComposer"` is shown there...

I just do not know what to do now... could you give me a hint? Is it needed to put in a special user-permission in the AndroidManifest.xml for instance or what am I doing wrong? 

Thank you very much for looking into this... I am quite new to phonegap and searched the web for different solutions but after trying all that I could find I am just stuck.
Thank you in advance for any help or hint you can give me :).

See you
*Fuchur*

**Comment by katzer** [comment]
@Fuchur84 I guess you have already fixed it. It seems like you are using a fork of my plugin. Either it has a bug or your cordova project is corrupted because `cordova-plugin-console 1.0.0 "EmailComposer"` makes no sense.
