### ISSUE TITLE
Unable to create external cache directory

### ISSUE THREAD

**Issue by marco-bransch** [katzer/cordova-plugin-email-composer#149]
Sehr geehrte Damen und Herren,

aktuell verwenden wir das Plugin "cordova-plugin-email-composer" in einem unserer Projekte. Auf einem Huawei Y530 unter Android 4.3 erhalten wir folgende Fehlermeldung.

![bildschirmfoto 2015-11-16 um 14 25 20](https://cloud.githubusercontent.com/assets/1257064/11182899/aaa5c06c-8c6e-11e5-87a5-53be2b3518fa.png)

Das Plungin wird wie folgt verwendet. In der Manifestdatei wurden die Berechtigungen "READ_EXTERNAL_STORAGE" und "WRITE_EXTERNAL_STORAGE" gesetzt.

<code>
var email = {
        to: 'm.bransch@academy.de',
        subject: 'Cordova Icons',
        body: 'How are you? Nice greetings from Leipzig',
        attachments: "base64:image.png//iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9YGARc5KB0XV+IAAAAddEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIFRoZSBHSU1Q72QlbgAAAF1JREFUGNO9zL0NglAAxPEfdLTs4BZM4DIO4C7OwQg2JoQ9LE1exdlYvBBeZ7jqch9//q1uH4TLzw4d6+ErXMMcXuHWxId3KOETnnXXV6MJpcq2MLaI97CER3N0vr4MkhoXe0rZigAAAABJRU5ErkJggg=="
      };
    cordova.plugins.email.open(email);
</code>

Wir wünschen Ihnen einen erfolgreichen Tag und würden uns über eine baldige Rückmeldung sehr freuen.

Mit freundlichen Grüßen
Marco Bransch

**Comment by katzer** [comment]
@marco-bransch Hallo Herr Bransch,

grundsätzlich hat die `Missing external cache dir` zur Folge, dass Anhänge nicht verwendet werden können.

Ein Grund ist, dass die Berechtigung __WRITE_EXTERNAL_STORAGE__ entzogen wurde (Gilt für Versionen älter als Android 4.4).

Der wahrscheinliche Grund in ihrem Fall ist wahrscheinlich, dass kein freier Speicher zur Verfügung steht.

Siehe Android Dokumentation:
```
Returned path may be null if a storage device is unavailable.
```
