### ISSUE TITLE
New line in text email

### ISSUE THREAD

**Issue by ekbee** [katzer/cordova-plugin-email-composer#150]
Dear,

I am using this plugin but cannot find newline character but it did not work

body: "\nDear Administrator,\n\nPlease kindly unlock my ID"

I try to find in document but not found. Please kindly shade me some light. Thank you.

**Comment by katzer** [comment]
The way how to achieve might vary between mail clients. Try out `<br>` or `\\n`!

**Comment by dtruel** [comment]
`<br>` worked for me.  Thank you

**Comment by pallaviMN** [comment]
@ekbee , i am facing same issue in android outlook
