### ISSUE TITLE
Example Please

### ISSUE THREAD

**Issue by haribabumsc** [katzer/cordova-plugin-email-composer#152]
Hi 
I am New into this domain, i tried to use this plugin but not getting success, can any one give me tip that how to use after install plugin in HTML page ? should i include js files ? if you any one send sample code would be helpful for me. Thanks in advance.

**Comment by mnewmedia** [comment]
This plugin works only native on phones like android or ios. cordova will autoload cordova plugins, so you don't have to include js files.
All plugins will be available in the global var `cordova.plugins` and you can use the plugins through this. But the readme is really good and easy documentet, I really don't know how to help you more. Maybe you should google for cordova tutorials..

**Comment by katzer** [comment]
:+1: Also see the example branch
