### ISSUE TITLE
Email Composer crashes in cordova iOS 4

### ISSUE THREAD

**Issue by racekarl** [katzer/cordova-plugin-email-composer#155]
When I try to call cordova.plugins.email.open in an iOS app built with cordova iOS platform version 4.0.0, my app crashes with the following error:

2015-12-14 19:59:54.333 Fivespark[1830:558512] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSData cdv_dataFromBase64String:]: unrecognized selector sent to class 0x1a1c8e8b8'
*** First throw call stack:
(0x18452d900 0x183b9bf80 0x184534514 0x1845315b8 0x18443568c 0x1001b20c0 0x1001b18cc 0x1001b150c 0x1001b0a00 0x1001aff58 0x1001afd18 0x1003ddbf0 0x1003ddbb0 0x1003ece10 0x1003ec4d8 0x184195470 0x184195020)
libc++abi.dylib: terminating with uncaught exception of type NSException

The following section of code is highlighted:

    #ifndef __CORDOVA_3_8_0
        NSData* data = [NSData dataFromBase64String:dataString];
    #else
        NSData* data = [NSData cdv_dataFromBase64String:dataString];
    #endif

I don't really know objective-C but if I had to guess the compiler directive was put in with the assumption that cordova iOS 3.8.0 was the latest and targeted the newest iOS, but now that 4.0.0 is out the code attempts to call an older method that no longer works.

**Comment by racekarl** [comment]
Well, I commented out the compiler directives so that only the 3_8_0 branch was active and it still crashed.

I forgot to mention that I am trying to send an attachment and this code is in APPEmailComposerImpl.m -dataFromBase64

**Comment by mnewmedia** [comment]
look here https://github.com/hypery2k/cordova-email-plugin

**Comment by katzer** [comment]
Has been fixed - Thanks!
