### ISSUE TITLE
Javascript Runtime Error from Email Composer Plugin in Windows Cordova App

### ISSUE THREAD

**Issue by chrysanhy** [katzer/cordova-plugin-email-composer#156]
I am attempting to send an email with an attachment in the base64 string format in a Cordova Windows Universal App running as a desktop app on Windows 10. This has worked a few times, but I am more often than not getting one of the following Javascript Runtime errors when running under Visual Studio 2015:

<code>Unhandled exception at line 302, column 9 in Function code
0x80070005 - JavaScript runtime error: Access is denied.
Unhandled exception at line 302, column 9 in Function code</code>

<code>Unhandled exception at line 302, column 9 in Function code
0x80070002 - JavaScript runtime error: The system cannot find the file specified.
Unhandled exception at line 302, column 9 in Function code</code>

Visual Studio displays the following line in <code>eval code [dynamic]</code>:

<code>var o = {};o["Windows.Foundation.IAsyncAction"] = function () { o["WinRT Promise.done()"](); };o["WinRT Promise.done()"] = function () { rethrowPromiseError(); };o["Windows.Foundation.IAsyncAction"]</code>

with the <code>rethrowPromiseError()</code> highlighted.

On one occasion doing a "Clean Solution" and rebuilding made this go away, but I have since been unable to reproduce that behavior. This happens with both Debug and Release builds.

Unfortunately there is no way to trap this error, so the app just crashes.

The problem is with the plugin's reading of the temp file after it creates it asynchronously, because creating the temp file myself with the file plugin and attaching it that way seems to work. Is the plugin waiting for completion of the write before proceeding?

**Comment by katzer** [comment]
@chrysanhy Has been fixed!
