### ISSUE TITLE
Attachment Issue 

### ISSUE THREAD

**Issue by globalizeme** [katzer/cordova-plugin-email-composer#157]
Hi there,

I'm using this plugin to send email; the email comes through but anything attached to the email doesn't. See the screenshot below. When the user clicks on 'Mail my Ingolf', a mail should be fired with the Ingolf image. The mail reaches the recipient but the attachment is lost.

I'd be grateful for a quick fix, thank you.

screen short : http://screencast.com/t/lup1bved2Gn

Kind regards,

**Comment by mnewmedia** [comment]
Show some code.. How can we help if you just say it's not working, cause for me it is working.

**Comment by katzer** [comment]
@globalizeme I've tried out sending attachments (any kind of types like images, pdf or base64) and sent them via iMail on iOS and Mail or Gmail on Android. - Always with success. The mail reaches the recipient with attachments.

Some code might be helpful.

**Comment by katzer** [comment]
@globalizeme It might be related to #149
