### ISSUE TITLE
PhoneGap Build - No Email Account Setup Error

### ISSUE THREAD

**Issue by bayhall-digital** [katzer/cordova-plugin-email-composer#159]
I'm having trouble with this plugin since moving to PGB cli-5.2.0

This plugin `<gap:plugin name="de.appplant.cordova.plugin.email-composer" spec="0.8.2" source="pgb" />` crashes the app when isAvailable is called. 

A forked version: `<gap:plugin name="cordova-plugin-email" source="npm" />` which I believe addresses the issue, simply hangs when isAvailable is called on either a device with or without an email account, but the App is still usable (can use the menu to move to other sections). Returning an error "undefined is not an object (evaluating 'cordova.plugins.email.isAvailable')"

Currently, the only plugin which partially works is `<gap:plugin name="cordova-plugin-email-composer" source="npm" />` and this incorrectly returns true when an account is not setup on a device.

**Comment by bayhall-digital** [comment]
OK - I've moved over to https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/ac66d5d/README.md which allows for more options for me, and lets the user decide how to export a file how they wish - could be a side step for anyone else experiencing this problem.

**Comment by katzer** [comment]
@bayhall-digital Can you try out if you have same issue with latest dev version? I've tested it with latest iOS, cordova-ios and without account and got no crash. Instead `isAvailable` returns correct information that no account is set up.
