### ISSUE TITLE
What about this for Windows 8 / 8.1?

### ISSUE THREAD

**Issue by Fuchur84** [katzer/cordova-plugin-email-composer#165]
http://developerpublish.com/windows-phone-8-1-and-windows-runtime-apps-how-to-2-send-emails-with-attachment-in-wp-8-1/

**Comment by katzer** [comment]
@Fuchur84 Its exactly what the plugin is using. By using the `cordova-windows` platform you can deploy apps for wp8, wp8.1 and windows universal.

**Comment by VPantaleo** [comment]
Hi, but not is javascritps ?

How function ?
