### ISSUE TITLE
iOS build error: Cordova/NSData+Base64.h file not found

### ISSUE THREAD

**Issue by bitflower** [katzer/cordova-plugin-email-composer#166]
I have an IONIC app (latest version 1.2.4) with Cordova 4.0.1.

After adding the plugin i get this error:
![bildschirmfoto 2016-02-12 um 21 01 57](https://cloud.githubusercontent.com/assets/6666636/13018846/556f610e-d1cc-11e5-9f3b-431b976c23d7.png)

XCode version 7.2.1 on OSX 10.10.5 Yosemite

**Comment by bobolat** [comment]
i got the same error with ios platform latest and cordova latest

**Comment by maryiam** [comment]
Same error. Any solution so far?

**Comment by xdoremus** [comment]
I am encountering the same error, too.

**Comment by bobolat** [comment]
temporarily i just downgrade cordova tu 5.1.1 and ios paltform to 3.9.1..i managed to build it since i need to upload the update i made on my apps to apps store

**Comment by jenssogaard** [comment]
Same here. Very keen on a fix.
XCode 7.2
Cordova CLI: 6.0.0

**Comment by skotturi** [comment]
Same issue here. Tried cordova@5.1.1 and cordova-ios@3.9.1 but didnt work for me.

**Comment by keegho** [comment]
Same error...???? Any solutions?

**Comment by skotturi** [comment]
I downgraded to `cordova@5.4.1` and `cordova-ios@3.9.2` and its working. I had to remove and re-add the ios platform in my app to get it working. Looks like its cordova v6 and its partner cordova-ios v4 thats causing the issue.

**Comment by katzer** [comment]
@bitflower, @skotturi Has been fixed. I am working on a new minor release within the next days.

**Comment by xdoremus** [comment]
Good news @katzer! Thanks a lot!

**Comment by JeremyColton** [comment]
I only see this bug when I run inside a iphone 5s  or 6 emulator (deploy target iOS 9.2).  Running on my real 5s phone, running ios 9.2, it's ok!  Anyone know what the difference could be?

**Comment by skotturi** [comment]
I had to downgrade from 0.8.3 to 0.8.2 in order to get Android permissions to work but this brings back this bug on iOS. I can run my app in debug on sim and on device, however, when I build for app store archive, it fails. Is it possible to run 0.8.3 for iOS and 0.8.2 for android? Or is this level of granularity not possible in cordova plugins?

**Comment by kigero** [comment]
I got this error as well with 0.8.2 (which I also needed for Android support), and I was able to get it to build both for devices and simulators by:

1. Manually downloading the [NSData+Base64](http://projectswithlove.com/projects/NSData_Base64.zip) package.
2. Adding the NSData+Base64.[h|m] files to the platforms/ios/CordovaLib/Classes/Public folder.
3. Adding those files to the same folder in Xcode.
This got things working for devices, but for the simulator it required an extra few steps:
4. Select the CordovaLib project, and go to the Build Phases tab.
5. Expand Headers.  There are three sections here, Public, Private, and Project.  The NSData+Base64.h header was added to the Project section for me.
6. Move the NSData+Base64.h file from the Project section to the Public section.
Now I could build for devices, simulator, and archive for the store.

**Comment by sanandiyavipul** [comment]
1. Just Remove **Cordova/NSData+Base64.h** file.

2.Remove this line **NSData* data = [NSData dataFromBase64String:dataString];** and add this new line **NSData* data = [[NSData alloc] initWithBase64EncodedString:dataString options:0];**

**Comment by Ramprasathselvam** [comment]
Refer this Link
[https://stackoverflow.com/questions/36348202/cordova-4-0-1-cdv-camera-cordova-nsdatabase64-h-not-found/52606879#52606879](url)
