### ISSUE TITLE
unable to send image via img tag in email body

### ISSUE THREAD

**Issue by donny08** [katzer/cordova-plugin-email-composer#167]
This is Snippet:
var image = "http://www.8coupons.com/image/deal/14783611"

var html = "<img src="+ image +"><br><a href=" + emailLink + ">dealTitle:" + dealData.dealTitle + "<br>dealinfo:" + dealData.dealinfo + "<br></a>";

cordova.plugins.email.open({
            app: 'mailto',
            subject: 'Localdeals',
            body:html,                     
            isHtml:  true
        })
In compose email it shows OBJ value for image

**Comment by matt-neill** [comment]
@donny08, did you get this figured out?  I'm currently running into this problem.

**Comment by alemartel** [comment]
@donny08  @matt-neill  any solution for this issue??

**Comment by matt-neill** [comment]
Nope.  I went back to my client and told them it wasn't possible within the budget.

**Comment by sabanad** [comment]
Did any one found any solution for this? I'm still unable to add image using img tag
