### ISSUE TITLE
No longer showing up on npmjs.org?

### ISSUE THREAD

**Issue by lunchbag** [katzer/cordova-plugin-email-composer#171]
Hi there,

In trying to install this plugin:
`cordova plugin add de.appplant.cordova.plugin.email-composer`

I keep getting this error:
`Fetching plugin "de.appplant.cordova.plugin.email-composer" via npm
Error: Failed to fetch plugin de.appplant.cordova.plugin.email-composer via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/de.appplant.cordova.plugin.email-composer`

The plugin no longer seems to be on npmjs.org. Has it been removed on purpose?

**Comment by lunchbag** [comment]
Nevermind, it shows up now but there is another error. Will create a new ticket.

**Comment by katzer** [comment]
@lunchbag When I am releasing the next version soon it will be published on npm.
