### ISSUE TITLE
isAvailable return false on API Level 23

### ISSUE THREAD

**Issue by transoceanic** [katzer/cordova-plugin-email-composer#177]
Possible, it related to Requesting Permissions at Run Time
[https://developer.android.com/training/permissions/requesting.html](url)

**Comment by AhsanAyaz** [comment]
+1 
I'm always getting isAvalable false on my nexus5 running marshmallow

**Comment by yipingw** [comment]
+1
issue from here:

> EmailComposerImpl.java

``` java
public boolean[] canSendMail (String id, Context ctx) {
        // is possible with specified app
        boolean withScheme = isAppInstalled(id, ctx);
        // is possible in general
        boolean isPossible = isEmailAccountConfigured(ctx);

        return new boolean[] { isPossible, withScheme };
    }
```

**Comment by Alkashi** [comment]
+1
Any news about that guys ?

**Comment by ceskomira90** [comment]
me too.

**Comment by Alkashi** [comment]
We're all OK that isAvailable return false but is anyone here who can send emails on the last version of Android ?

**Comment by kentalogic** [comment]
+1
I have same problem. "isAvalable" method always return false.

**Comment by ratancs** [comment]
+1 

Is there any workaround or any other plugin to send email in latest versions of android.

**Comment by kukikiloke** [comment]
+1
For me it happens on both Marshmallow (6.0.1) and Lollipop (5.1.1)

**Comment by kentalogic** [comment]
this is my latest repository. it seems this problem has been resolved.
https://github.com/kentalogic/cordova-plugin-email-composer.git

**Comment by tomchiverton** [comment]
I'd like to try that as an alternative version on PhoneGap build, but it doesn't like me ( http://community.phonegap.com/nitobi/topics/unable-to-use-plugin-from-git-cannot-find-plugin-xml-for-plugin?rfm=1 ). 

Do you happen to know the correct <plugin> tag to use ?

**Comment by Alkashi** [comment]
@kentalogic same error as tomchiverton. Build cordova failed on android when target is android-22  :/

**Comment by shankari** [comment]
This is the same as issue #175.
It is not related to a particular API version - all of android is broken. 
#175 has a description of the problem, a proposed fix and a pull request.
We have to see whether the maintainers will merge the fix.

**Comment by BugsBunnyBR** [comment]
@kentalogic , thank you for your work! It works, the only problem is that, in the first time you run the code, when the user is prompted with the permission dialog, even if the user press "allow", the code does not ran, the user needs to trigger the email action again.

**Comment by joewoodhouse** [comment]
@kentalogic @BugsBunnyBR I think the reason you're having problems with that PR is that you've implemented it as if cordova.requestPermissions is synchronous. As per the documentation, you need to implement the onRequestPermissionsResult method to actually handle what the user returns, and from there then actually do what you want.

An alternative workaround to fixing the plugin for now is to use the cordova-plugin-diagnostic plugin to make the permission request, before running this plugin. e.g.

```js
cordova.plugins.diagnostic.requestRuntimePermission(function(status) {
  switch (status) {
    case cordova.plugins.diagnostic.runtimePermissionStatus.GRANTED:
      // Run the plugin
      cordova.plugins.email.isAvailable(function(isAvailable) {
        //etc...
      });
      break;
    case cordova.plugins.diagnostic.runtimePermissionStatus.NOT_REQUESTED:
    case cordova.plugins.diagnostic.runtimePermissionStatus.DENIED:
    case cordova.plugins.diagnostic.runtimePermissionStatus.DENIED_ALWAYS:
      console.log('Nope!');
      break;
  }
}, function(err) {
  console.log('Error:',err);
}, cordova.plugins.diagnostic.runtimePermission.GET_ACCOUNTS);
```

**Comment by maroselo** [comment]
+1

**Comment by skotturi** [comment]
+1 

was able to get it working again on N5 running 6.0.1 by reverting to `0.8.2`

```
cordova plugin remove cordova-plugin-email-composer
cordova plugin add https://github.com/katzer/cordova-plugin-email-composer.git#cab303d
```

**Comment by sava999** [comment]
One stupid question. If you only need email compose, without attachments, why don't you use [mailto](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Email_links)?

**Comment by skotturi** [comment]
@sava999 that would be great, except it forces the user to leave my app (it opens the mail app on ios) and then once they send the email they have to navigate back to my app (although now they're staring at their inbox and will probably get distracted and perhaps not come back). i'd much prefer to keep them in the app.

**Comment by sava999** [comment]
@skotturi makes sense. Thank you for explanation.
