### ISSUE TITLE
cordova.plugins.email.open fires callback immediately without doing anything

### ISSUE THREAD

**Issue by pierrekilly** [katzer/cordova-plugin-email-composer#178]
Hello!

I have a problem since I updated this plugin: it doesn't send any emails anymore.

When I call isAvailable with a sheme (gmail) on android, isAvailable is false and withScheme is true.

After that, when I call open with options and a callback, the callback is called immediatly without doing anything...

I don't see any message in the web console or android monitor.

Could you please help me?

Thanks a lot!

**Comment by kukikiloke** [comment]
I have the exact same problem!

**Comment by cdarken** [comment]
I think I have the same issue, after upgrading to cordova 6, but this might not be related.
The issue is on Android 6.

**Comment by IliasElJaouani** [comment]
Same problem here on Android 5.1.1

**Comment by szanellato93** [comment]
I have the same problem on my device. Any solution???

**Comment by IliasElJaouani** [comment]
The only thing that made it work on my Android Lollipop is removing the plugin and installing this version : 
cordova plugin add https://github.com/katzer/cordova-plugin-email-composer.git#0.8.2

But this makes my ios platform un-buildable... So do this only if you are only developing an android app

**Comment by szanellato93** [comment]
Thanks for your answer. How can i install it? I tried cordova plugin add cordova-plugin-email-composer@0.8.2 but nothing work :(

**Comment by IliasElJaouani** [comment]
Yeah you should add it like I did:
cordova plugin add https://github.com/katzer/cordova-plugin-email-composer.git#0.8.2

try with this syntax

**Comment by szanellato93** [comment]
Yeah with that all work well. There isn't a command to install this plugin only for Android? And use the other for iOS device?

Thank you for your help.

**Comment by IliasElJaouani** [comment]
You're welcome ! 

That's exactly the solution i'm looking for. Tried with Plugman, but couldn't manage to do it. 
Let me know if you find something !

**Comment by szanellato93** [comment]
I think this can help us: http://stackoverflow.com/questions/23108342/install-cordova-plugin-for-one-platform-only

i can't test it atm.. Tell me if it work, if you test it!

**Comment by katzer** [comment]
I've added a `forceOpen` method which works like `open` however it does not care about availability of an email client, permissions granted, ... c7a9b2c
