### ISSUE TITLE
Skype,Gallery vault,Line,Shareit displays in the list

### ISSUE THREAD

**Issue by manoj529** [katzer/cordova-plugin-email-composer#179]
Hi Developer,
Thank you, for sharing the plugin. It works great.however the list includes skype,shareit,line into the list of email apps present in the mobile.is there any way to filter these apps from the list and show only email apps. Thank you for any help regarding this.

**Comment by VPantaleo** [comment]
Hi, 
In my WIndows 10 the list is open only fist excute, why ?

What OS use ?

Thanks

**Comment by katzer** [comment]
Android has no 100%-Email framework. All of the listed apps have declared to the OS, that they are open to receive intents for email like messages.
