### ISSUE TITLE
Help with IOS

### ISSUE THREAD

**Issue by InventivHealthLondon** [katzer/cordova-plugin-email-composer#182]
Hi, I'm running ios 9.2.1, xcode 7.2.1, cordova 6.0.0 and I can't get anything to fire, perform. The function:

cordova.plugins.email.isAvailable(
    function (isAvailable) {
        alert('Service');
    }
);

doesn't even do anything. Am I doing something completely wrong the demo doesn't even work!

**Comment by graphefruit** [comment]
@InventivHealthLondon did you try it with an emulator or with a real device?

**Comment by oscarjiv91** [comment]
I'm having the same problem. But if I enter in Safari from my phone and run this code, it works. I'm using iOS 9.3.1

**Comment by xavipedrals** [comment]
I'm on the same issue using an iPad Air with iOS 9.2, any call made to the pluguin does nothing. Any solution?

**Comment by katzer** [comment]
I've added a `forceOpen` method which works like `open` however it does not care about availability of an email client, permissions granted, ... c7a9b2c
