### ISSUE TITLE
Windows 10 Mobile UAP > Get this problem...

### ISSUE THREAD

**Issue by Fuchur84** [katzer/cordova-plugin-email-composer#183]
Getting this in Visual Studio-JS-Console after activating the email plugin: 
APPHOST9613: The app couldn’t navigate to ms-appx-web://{name.of.app}/www/[object Object] because of this error: 80004005.

Any idea what is going on?

See you
_Fuchur_

**Comment by MilindSuryawanshi** [comment]
I am also facing same error, while opening a pdf, 

could any one help?

~

**Comment by katzer** [comment]
@Fuchur84 

> Getting this in Visual Studio-JS-Console after activating the email plugin

What do you mean with "activating"?

**Comment by katzer** [comment]
@MilindSuryawanshi 

> I am also facing same error, while opening a pdf

Would be helpful if you provide an URL you use for the attachments to reproduce that.
