### ISSUE TITLE
Help me! Windows 10 Attachment

### ISSUE THREAD

**Issue by VPantaleo** [katzer/cordova-plugin-email-composer#185]
Hi,

Please, Help me.
Why not function attanchment in Windows 10 mobile and Windows 10 desktop ?

Thanks

**Comment by Alkashi** [comment]
Hi @VPantaleo 

Did you find the solution ?

**Comment by VPantaleo** [comment]
Hi, 
In Windows it is important to set the recipient even with "" will not work

**Comment by Alkashi** [comment]
Hi @VPantaleo

Yes it works thanks.
But unfortunately it doen't work with Outlook 2016 :/ Only with Courrier.
