### ISSUE TITLE
Plugin doesn't work on Android

### ISSUE THREAD

**Issue by szanellato93** [katzer/cordova-plugin-email-composer#186]
I'm trying to send a simply email on my android device with this plugin but it doesn't work. I tested it on some Android device with some Android version. After i call the function:

```
cordova.plugins.email.open({app: 'mailto'}, function () {
    console.log('email view dismissed');
}, this);
```

the callback is immediatly trigged and nothing happen. On Ios all work very well.

**Comment by graphefruit** [comment]
Having the same issue now after upgrading.
I'm getting the error that "fn" is not a function.

**Comment by helzgate** [comment]
i had the same issue, latest plugin with latest cordova 6.0.0.  I ended up using cordova-plugin-email instead.

**Comment by graphefruit** [comment]
@helzgate I ended up trying cordova-plugin-email now aswell, but without success. Added via this source: http://ngcordova.com/docs/plugins/emailComposer/ or isn't this the right one?
Doesn't work for me neither, updated cordova from 5.3 to 6.0 plugin just says it isn't available.

**Comment by helzgate** [comment]
[This one](https://www.npmjs.com/package/cordova-plugin-email)

**Comment by jdflaugergues** [comment]
Same issue for me since I've update my corodova cli version to 6.0.0.
On iOS (cordova verison 4.0.1) it's work but on Android (cordova version 5.1.1) it's fail.

The code below return : "Service is not available" and I don't know why.
```
cordova.plugins.email.isAvailable(
    function (isAvailable) {
        console.log('Service is not available.');
    }
);
```

Try to use the cordova-plugin-email. !

**Comment by szanellato93** [comment]
I solved this problem by installing this:

cordova plugin add https://github.com/katzer/cordova-plugin-email-composer.git#0.8.2

**Comment by jdflaugergues** [comment]
Thanks @szanellato93.
Finally, I've switched on the fork of @hypery2k until this issue is resolved.

**Comment by graphefruit** [comment]
I tried 0.8.2 aswell, and it didn't have an effect on my side. The fork on hyper2k is working on my side without problems.

**Comment by IliasElJaouani** [comment]
I see that hypery2k's fork only works for max iOS8 and Android L , can somebody confirm please ? I absolutely need to target iOS9 and Android M

**Comment by graphefruit** [comment]
@IliasElJaouani I used Android L and M (5.0 and 6.0) and on both devices this plugin works.
I'll test it on an iOS9 device for you  today and give you feedback

**Comment by IliasElJaouani** [comment]
Thanks a lot Graphefruit

**Comment by graphefruit** [comment]
Short update @IliasElJaouani I asked this question already (hasn't it on my mind) have a look here: https://github.com/hypery2k/cordova-email-plugin/issues/7

PS: I'll still test it for you this afternoon ;)
Greetings

**Comment by IliasElJaouani** [comment]
Alright thanks @graphefruit, i'm using the new cordova 6.1.0 version, with cordova android 5.1.1 and cordova iOS 4.1.0 platforms

**Comment by jdflaugergues** [comment]
Hi @IliasElJaouani, the fork of @hypery2k and it works on iOS 9.0
You can try it.

**Comment by IliasElJaouani** [comment]
@jdflaugergues  thanks, i'll try it tonight when I get access to my Mac

**Comment by Farsk** [comment]
To get it working both on iOS and Android I had to use these settings in my config.xml...
`...
	
	<preference name="AndroidPersistentFileLocation" value="Compatibility" />
...
	
	<platform name="ios">
		<plugin name="cordova-plugin-email-composer" source="npm" version="0.8.3" />
	</platform>
	<platform name="android">
		<plugin spec="https://github.com/katzer/cordova-plugin-email-composer.git#0.8.2" source="git" />
	</platform>
...`
And this JS to open the email program...
`			cordova.plugins.email.open({
				subject: subject, //string
				body: body, //string
				attachments: attachments //array of fileURIs
			}, myFakeCallback); //callback is NOT optional`
Note: On Android the attachment fileURIs were the paths starting with "file:///storage/emulated/0/"

**Comment by Kinzi** [comment]
#0.8.2 works on Android but apperently does not on iOS:
https://github.com/katzer/cordova-plugin-email-composer/issues/141
Unfortunately @Farsk 's config hack didn't work for me.
-> Please fix this! ;-)

**Comment by tahoura** [comment]
HI,

I follow the code posted by @Farsk but doesn't work. I have as a result a white page. I tested the code with my phone Android Kitkat(4.4.2). Can you help me ?

**Comment by smika01** [comment]
Hello!
Same problem for me. Actual version didn't work on Android. Installation of version 0.8.2  as following did solve the problem for now:

cordova plugin add https://github.com/katzer/cordova-plugin-email-composer.git#0.8.2 

Any idea how to solve this problem in a last stable version?

Regards 
Sebastian

**Comment by xiaofanwu** [comment]
I have the same problem. Did anyone find a solution?

**Comment by tsofiyai** [comment]
Hello!
I had the same problem.
The solution I found on StackOverflow was to use plugman. It enables adding a specific version of a plugin to target a specific platform.
The steps I followed:
1.	Install plugman via: 
`npm install -g plugman`
2.	Install the latest version of the plugin only for ios: 
`plugman install --platform ios --project platforms/ios --plugin https://github.com/katzer/cordova-plugin-email-composer.git`
3.	Install version 0.8.2  of the plugin only for android: 
`plugman install --platform android --project platforms/android --plugin https://github.com/katzer/cordova-plugin-email-composer.git#0.8.2`
I am not sure this is the best solution, but it worked for me.
Hope is helps.

**Comment by LebToki** [comment]
still unsuccessful!
tried all route and they all led to failures :(

`
restaurantOrderProcessor.$inject = ['$filter', '$cordovaEmailComposer', '_', '$q'];

	/* @ngInject */
	function restaurantOrderProcessor($filter, $cordovaEmailComposer, _, $q) {

		var service = {
			performHomeDelivery: performHomeDelivery,
			sendTakeAwayConfirmation: sendTakeAwayConfirmation,
			sendDineInConfirmation: sendDineInConfirmation
		};
		return service;
`

Then individual services to invoke an email such as delivery. take away...

`
function sendEmail(to, subject, body) {
			try {
				return $cordovaEmailComposer.isAvailable().then(function() {
					var email = {
						to: to,
						subject: subject,
						body: body
					};

					$cordovaEmailComposer.open(email);

				});
			} catch (e) {
				return $q.reject('$cordovaEmailComposer is not available or failed. Are you running the app within a browser?');
			}
		}
`

Can someone please help !?

**Comment by katzer** [comment]
I'Ve updated the code right now and added support for granting permissions (Android)

**Comment by sriharibalgam** [comment]
Discovered plugin "cordova-plugin-email-composer" in config.xml. Adding it to the project
Fetching plugin "cordova-plugin-email-composer@~0.8.15" via npm
Installing "cordova-plugin-email-composer" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 6.1.2, failed version requirement: >=6.2.0
Skipping 'cordova-plugin-email-composer' for android
Installing "cordova-plugin-email-composer" for ios

in config.xml
 <plugin name="cordova-plugin-email-composer" spec="~0.8.15" />
