### ISSUE TITLE
Callback on Android.

### ISSUE THREAD

**Issue by mseleng** [katzer/cordova-plugin-email-composer#188]
Is there a way how to tell whether an email has been sent or not on Android? 
I know that there is a possibility on iOS to add a parameter to the callback.
Isn't something similar possible in Android?
I am using this plugin via ngCordova and in its sources I can see, that it only does `q.reject()` in callback (no check for the platform, etc.) which removes any possibility to make kind of "success callback"
Thanx for the response.

**Comment by maroselo** [comment]
Okay, so I read something about Intents and I can see, that it is not possible to do it.

I think the issue can be closed unless anyone has anything on it.
