### ISSUE TITLE
Cordova 6.1.1 plugin doesn't work

### ISSUE THREAD

**Issue by tahoura** [katzer/cordova-plugin-email-composer#197]
Hi ,

I try to use the plugin with Android 4.4.2 and cordova 6.1.1. I write  in config.xml
`<preference name="AndroidPersistentFileLocation" value="Compatibility" />
<platform name="android">
        <allow-intent href="market:*" />
        <plugin spec="https://github.com/katzer/cordova-plugin-email-composer.git#0.8.2" source="git" />
    </platform>`
I install with command 

> :cordova plugin add https://github.com/katzer/cordova-plugin-email-composer.git#0.8.2

In js i write
`cordova.plugins.email.open({
    to:      'max@mustermann.de',
    cc:      'erika@mustermann.de',
    bcc:     ['john@doe.com', 'jane@doe.com'],
    subject: 'Greetings',
    body:    'How are you? Nice greetings from Leipzig'
})`

I call th js in html with

`<input type="button" onclick="open()" value="Send mail" />`

As a result i have a blank page .

Can you help me

**Comment by Alorse** [comment]
It is the version of the android
https://github.com/katzer/cordova-plugin-email-composer/issues/193
