### ISSUE TITLE
Fail when tries to attach WhatsApp images (Android)

### ISSUE THREAD

**Issue by JuanjoSalvador** [katzer/cordova-plugin-email-composer#201]
I'm working in an application that it is be able to send images by email. Works fine, but when I try to attach an image from WhatsApp gallery, image doesn't appears in email application. I guess it is a permission fail.

With images from another location (from any folder of my SD card or internal memory) works fine.

**Comment by katzer** [comment]
Missing permission can be the case. Guess you tried to set them in the manifest. I've tested only SD card and app folders. In theory it should work if the path is absolute and permissions are granted.
