### ISSUE TITLE
isEmailAccountConfigured acconts error

### ISSUE THREAD

**Issue by hiniesta** [katzer/cordova-plugin-email-composer#202]
In Android, there is an error in function isEmailAccountConfigured of the file EmailComposerImpl.java. It doesn't detect as valid accounts types such as Google accounts or Exchange Accounts.

**Comment by juhasuni** [comment]
I just posted a pull request #206 that fixes the issue.

**Comment by AlexandraNau** [comment]
I will close the issue, because there is another one regarding the same topic. Please take a look at issue #228.
