### ISSUE TITLE
When i try to add this plugin into my ionic app it always show me this issue ??Any Help Please

### ISSUE THREAD

**Issue by mhmdbj** [katzer/cordova-plugin-email-composer#208]
Error: Failed to fetch plugin https://github.com/katzer/cordova-plugin-email-composer.git via git.
Either there is a connection problems, or plugin spec is incorrect:
Error: "git" command line tool is not installed: make sure it is accessible on your PATH.

**Comment by Langstra** [comment]
```
sudo npm install git-all
```

**Comment by AlexandraNau** [comment]
I am closing this issue now, because @Langstra 's comment seemed to have helped.
