### ISSUE TITLE
No default email app configured.

### ISSUE THREAD

**Issue by Moghul** [katzer/cordova-plugin-email-composer#211]
Alright... plugin worked fine for a long time. Then, I updated to Cordova CLI 5.4.1 and 0.8.3. Just today, I tapped the button to send an email and a popup came up with 

`No default email app configured.`

Tested on two devices, both say the same thing.

Any ideas?

**Comment by timothystewart6** [comment]
Have you launched and configured the default mail app?

**Comment by Moghul** [comment]
There's a Gmail app installed.
I am signed into it with multiple accounts.
I get emails on there daily.
Before now, at the very least it would ask me which app I wanted to complete the action with.

**Comment by florentsuc** [comment]
Same error for me on Android.

`cordova.plugins.email.isAvailable()`

Returns me `false`. And I have Gmail installed on my Android device.

**Comment by florentsuc** [comment]
BTW, duplicate #209

**Comment by skicson** [comment]
I'm seeing the same issue on my android test device that has gmail configured.  Tracked it down to line 518 in EmailComposerImpl.java, function isEmailAccountConfigured.  When I print out the account.type, I get _com.google_, but it is expecting that the type end with "mail".

**Comment by gigeos** [comment]
Not work on Samsung S4 running 5.0.1 too

**Comment by mials** [comment]
try this
cordova plugin rm cordova-plugin-email-composer
cordova plugin add https://github.com/katzer/cordova-plugin-email-composer.git#0.8.2

  cordova.plugins.email.open({
      to:      ' ',
      subject: ' ',
      body:    ' email ',
      isHtml:  true
  });
https://github.com/katzer/cordova-plugin-email-composer

**Comment by jedofus** [comment]
it's work for me on Android Platform but i have error on Ios Platform : 
      'Cordova/NSData+Base64.h' file not found
#import "Cordova/NSData+Base64.h"

**Comment by Moghul** [comment]
@jedofus That's a different issue, mate.

@mials I ended up going with a different plugin in the end. I'll leave this issue open 'till it's fixed but you can close it when it is.

Everyone, have a great day.

**Comment by pabloim1** [comment]
@mials Which plugin did you use?

**Comment by mials** [comment]
@pabloim1 i use https://github.com/katzer/cordova-plugin-email-composer.git#0.8.2 and and it works on mobile parfatement andoid but not in browser

**Comment by Moghul** [comment]
I used this com.jcjee.plugins.emailcomposer
It doesn't do everything but it works.

**Comment by AlexandraNau** [comment]
Hello everyone,
instead of checking the account.type now the account.name is checked. Hopefully this will solve this issue.

Best regards,
Alex
