### ISSUE TITLE
Alternative implementation

### ISSUE THREAD

**Issue by ihadeed** [katzer/cordova-plugin-email-composer#212]
Hey there,

Thanks for your efforts on building this useful plugin.

I wanted to ask some questions for the sake of clarification, and also suggest a few things.

---
1. Why is there a `scope` parameter in your methods? How does this become beneficial for the developer?
2. Cordova plugins usually have the last two parameters as `successCallback` and `errorCallback`. Is there a reason why you only have `callback` there? Are you open for a PR that changes the approach to have two callbacks? Perhaps, they could be the first two parameters since the rest are optional?

**Comment by katzer** [comment]
Hello @ihadeed The scope will be the scope of the function, otherwise its `windows`

```js
email.open(app.onSent, app);
```

When the plugin invokes the callback, `this` will never to what you would expect: `app`.

**Comment by katzer** [comment]
The callbacks are optional as well. The internal code also does not differ between between success or failure. In case of this plugin, I see it as not necessary to have 2 callbacks.

**Comment by ihadeed** [comment]
Thanks for the response
