### ISSUE TITLE
GET_ACCOUNTS permission

### ISSUE THREAD

**Issue by pliablepixels** [katzer/cordova-plugin-email-composer#215]
Hi there, this plugin requires GET_ACCOUNTS to read the state of any account. This particular permission is rather permissive https://developer.android.com/reference/android/Manifest.permission.html#GET_ACCOUNTS and includes access to social accounts too.

Is there any way to avoid this? Thank you.

**Comment by pliablepixels** [comment]
closing, switched to another plugin

**Comment by ashwinputhige** [comment]
@pliablepixels Which plugin did you switch to?

**Comment by pliablepixels** [comment]
@ashwinputhige com.jcjee.plugins.emailcomposer 1.4.6 "Email Composer with Attachments"
