### ISSUE TITLE
callback method on cordova.plugins.email.open doesn't return anything

### ISSUE THREAD

**Issue by mrbaljit** [katzer/cordova-plugin-email-composer#221]
callback method on cordova.plugins.email.open returns null. So I am sure if user has clicked on cancel button or send button. Anyone can help please?

**Comment by frey1esm** [comment]
@hunnysharma102  This is different issue. This issue @mrbaljit mentions is with `email.open`.  The issue you reference is with `email.isAvailable`.

On ios, the `email.open` callback returns null on success or failure. It would be expected to return `true` on success, `false` on failure.

**Comment by carlosg85** [comment]
it would be perfect! i need to know if the email has been sent or cancelled, to do something in each case.
Anybody helps me?

**Comment by katzer** [comment]
@mrbaljit I guess you encountered a bug in cordova-android. I don't know the exact version however they had a bug with callbacks methods who have multiple arguments. That has been fixed at least with the recent version.
