### ISSUE TITLE
Compatibility with Outlook 2007

### ISSUE THREAD

**Issue by inane** [katzer/cordova-plugin-email-composer#222]
Hello,

I am implementing the solution in Windows 8 and iOS, but I am having a problem with Outlook 2007 and it is not working, with Outlook web access and Mail (iOS) is working correctly..  Plugin has compatibility with this Outlook version?

Thank you.

**Comment by mareksip** [comment]
Hello, plugin probably supports only [Mail ](https://www.microsoft.com/en-us/store/p/mail-and-calendar/9wzdncrfhvqm)app, has to be set to default.

**Comment by katzer** [comment]
@inane The plugin does not invoke the mail client directly. If the OS does identify the outlook app as a mail client it should work.
