### ISSUE TITLE
Attachment not working on Windows Desktop

### ISSUE THREAD

**Issue by georgeslegros** [katzer/cordova-plugin-email-composer#223]
Hello,

I'm having issues getting the the attachment to work on Windows Desktop while it works perfectly on WP10.

I have to say that I did not test Android and iOS yet but I guess this is related to Windows Desktop.
The behavior is actually strange: is opens my Outlook (2016 in case this is important) with all the inforamtions (to, subject, body) but the attachment is jut not there. Also it does print out the following in the console: "Cannot open app" but it seems like it does the same on WP10.

I'll do more tests tomorrow for iOS and Android and will post the results.

Anybody experiencing the same result?

Thanks,

Georges

**Comment by Alkashi** [comment]
Hi @georgeslegros 

I have the same issue. Did you find any fix that works ?
Thx.

**Comment by Alkashi** [comment]
Hi all,

Anybody has an idea about how to solve this isue please ?

**Comment by mareksip** [comment]
My opinion is that this plugin only work with Windows default [Mail app](https://www.microsoft.com/en-us/store/p/mail-and-calendar/9wzdncrfhvqm), not Outlook.

**Comment by katzer** [comment]
Thats true, only default app. Their framework does not allow to specify or discover other mail clients.
