### ISSUE TITLE
In ioS, it doesn't ask options of mail app.

### ISSUE THREAD

**Issue by donny08** [katzer/cordova-plugin-email-composer#224]
cordova 5.4.0.
I have installed Cordova email composer plugin using cordova plugin add cordova-plugin-email-composer cmd. I have wrote code for sending email below code snippet:
cordova.plugins.email.open({
    to:      'max@mustermann.de',
    subject: 'Greetings',
    body:    '<h1>Nice greetings from Leipzig</h1>',
    isHtml:  true
});

When I call above function it only opens default email app doesn't ask for mail app options, this happens only in ios. On Android all work very well.

**Comment by ominfowave** [comment]
i have same issue

**Comment by katzer** [comment]
Different OS, different behaviour.
It opens the iOS app without any chooser as its not a share-with plugin.
