### ISSUE TITLE
Build Fails after adding the plugin

### ISSUE THREAD

**Issue by Ramkumar14** [katzer/cordova-plugin-email-composer#226]
ANDROID : Please refer the CLI screenshot in the below comment.

**Comment by Ramkumar14** [comment]
![2016-07-26_155200](https://cloud.githubusercontent.com/assets/5800945/17134885/5b2d7180-534a-11e6-9a31-9bbd60866031.png)

**Comment by Ramkumar14** [comment]
But once after removing the plugin, build works. Did i miss anything? i'm New to cordova development. pls help.

**Comment by ubaidsaeed** [comment]
Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: de.appplant.cordova.plugin.email-composer

**Comment by katzer** [comment]
Plugin id is cordova-plugin-email-composer
