### ISSUE TITLE
Error in email account detection on android

### ISSUE THREAD

**Issue by corran2go** [katzer/cordova-plugin-email-composer#228]
In `EmailComposerImpl.isEmailAccountConfigured`

there is a check for available mail accounts on the device via
`if (account.type.endsWith("mail")) {`

but this fails e.g. when there is a gmail account configured as it returns "com.google" on my HTC test phone.

**Comment by cjs1976** [comment]
Hi, did you find a solution? I have the same problem. Works on old Android 4, but not on newer ones. Thanks, Christian.

**Comment by marco-bransch** [comment]
Problem solved. Please see following fork https://github.com/starhealthcare/cordova-plugin-email-composer

**Comment by AlexandraNau** [comment]
Hello everyone,
instead of checking the account.type now the account.name is checked. Hopefully this will solve this issue.

Best regards, 
Alex
