### ISSUE TITLE
email-composer crashes

### ISSUE THREAD

**Issue by swamikarthi123** [katzer/cordova-plugin-email-composer#230]
**email-composer plugin crashes on iOS 9.3.2** it works fine in the previous versions from 9.2.1 and below

**Comment by prasadyallapu** [comment]
Can any one look in to this issue @katzer .Email plugin crashes in ios10 version.

**Comment by AlexandraNau** [comment]
I will close this issue, because there are multiple issues regarding this topic. Please track #246.
