### ISSUE TITLE
email composer plugin is not working in iphone

### ISSUE THREAD

**Issue by ominfowave** [katzer/cordova-plugin-email-composer#232]

**Comment by arcadius** [comment]
@ominfowave, please could you give more detail about this issue such as:

- iOS version
- error message and stacktrace?

It would be VERY helpful if you could spend some time on this and capture a stacktrace .... this will help a lot.

Many thanks.

**Comment by ominfowave** [comment]
iphone 6s and isAvailable method always return false then not open any email app

**Comment by AlexandraNau** [comment]
I will close this issue, because there are multiple issues regarding this topic. Please track issue #211.
