### ISSUE TITLE
isAvailable return false in iphone

### ISSUE THREAD

**Issue by ominfowave** [katzer/cordova-plugin-email-composer#234]
please give me solution

**Comment by luisfsteixeira** [comment]
Also facing same issue, 
Ios 9.3.4; 
Cordova 6.0.0;
ios-platform 4.1.1;
plugin 0.8.3.

Works on simulator, fails on real Iphone 5 running IOs 9.3.4

**Comment by miloslavskacel** [comment]
Also facing the same issue

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
ios-deploy version: 1.8.6 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.8.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by AlexandraNau** [comment]
I will close this issue, because there are multiple issues regarding this topic. Please track issue #211.
