### ISSUE TITLE
can not build/run the example

### ISSUE THREAD

**Issue by ZhipengZeng** [katzer/cordova-plugin-email-composer#235]
I simply downloaded the example.
After I input `cordova run android` in command line, it shows this error below.

I am using usb connected Nexus 5X as my testing device.

![image](https://cloud.githubusercontent.com/assets/9456989/17834812/a8e3636a-671f-11e6-88da-c2e220e2349d.png)

Any places that I missed? Thanks in advanced.

**Comment by katzer** [comment]
:) Its best if you remove and then add the platforms again
