### ISSUE TITLE
<br> tag not working in outlook app of android

### ISSUE THREAD

**Issue by pallaviMN** [katzer/cordova-plugin-email-composer#239]
Hi Team,

I used <br> in my body & used "isHTML" true but its not coming properly

Hi <br> I am a developer.

I expect it to come as 

Hi
I am a developer.

But its working in gmail & email apps of android

**Comment by pallaviMN** [comment]
Not only br tag any HTML elements not working in android outlook 2.1.65 version

**Comment by jasminpethani** [comment]
i am facing the same issue does anyone found solution regarding this ?

**Comment by pallaviMN** [comment]
@jasminpethani 

Please use below code

 private void setBody (String body, Boolean isHTML, Intent draft) {
        if (isHTML) {
            draft.putExtra(Intent.EXTRA_TEXT, Html.fromHtml(body));
            draft.setType("text/html");
            body = body.replace("<br/>", System.getProperty("line.separator"));//added to fix outlook error

            if (Build.VERSION.SDK_INT > 15) {
               // Log.d(LOG_TAG, "Called here: ");
                //draft.putExtra(Intent.EXTRA_HTML_TEXT, Check);//added to fix outlook error
            }
        } else {
            Log.d(LOG_TAG, "Called here only: ");
            draft.putExtra(Intent.EXTRA_TEXT, body);
            draft.setType("text/plain");
        }
    }

**Comment by pallaviMN** [comment]
@jasminpethani , let me know if it works

**Comment by jasminpethani** [comment]
It works any solution for windows  because when I open email in Outlook it
doesn't encode html.

**Comment by katzer** [comment]
Well blame Windows or Android. The mail clients for Android usually have no HTML supported. They only support rich formatted text.
