### ISSUE TITLE
repo doesn't seem to be maintained 

### ISSUE THREAD

**Issue by taljacobson** [katzer/cordova-plugin-email-composer#241]
this repo hasnt been maintained it awhile and most of the issues get closed by the issue auther

this fork seems like the most up to date

https://github.com/hypery2k/cordova-email-plugin

**Comment by miparnisari** [comment]
I second that, the readme should be edited to say so. Otherwise it's very confusing.

**Comment by CheetahDev** [comment]
Hi @katzer, any confirmation on this topic? Thanks

**Comment by katzer** [comment]
@taljacobson, @CheetahDev It's maintained but I cannot work on it every day.

**Comment by mobidev111** [comment]
Last commit is of March. At the same time there are numerous pull requests sitting waiting. 

How can we come to a situation where once a month some gardening takes place? Do you need someone to help? We can seek support among the contributors..

**Comment by katzer** [comment]
@mobidev111 That would great. Sorry for the late reply. I get tons of GitHub mails every day and had to set a filter.
