### ISSUE TITLE
Can't send emails if device only has one email client

### ISSUE THREAD

**Issue by chocolette227** [katzer/cordova-plugin-email-composer#242]
The organization I work for uses this plugin to facilitate sending emails from an internally developed mobile app.  The devices said app is installed on are being restricted using IBM's MaaS360 application, which we use to disable the non-Gmail email client that comes on the samsung android tablets we use.  The only client left is Gmail, which creates a problem at line 208 in this file: 
https://github.com/katzer/cordova-plugin-email-composer/blob/f4fcee88c47c7ac642cceb27d3d8b31edd26a8f6/src/android/EmailComposer.java
... since the tablet only has one email client available.  Changing ">1" to ">0" should fix the problem.

**Comment by Gerjo** [comment]
Have you tried updating to newer code? Line 208 doesn't exist in the master branch anymore.

**Comment by chocolette227** [comment]
We decided to fork the repo and make our own fix, but I logged this issue in case anyone else bumps into this problem.  It looks like implementing the newest code should fix the problem, as you suggested.  I think it's safe to close this.
