### ISSUE TITLE
Unable to open email client

### ISSUE THREAD

**Issue by Priyansh** [katzer/cordova-plugin-email-composer#243]
Hello folks,

I had tried everything to use this cordova-plugin-email-composer in my cordova based phonegap application. when  I am using below code that complains me through chrome browser inspect  shows **"Cannot read property 'email' of undefined" *\* , how ever I already used **"email_composer.js"**in my index.html file. Additionally, I already included <gap:plugin name="cordova-plugin-email-composer" version="0.8.3" source="npm" /> in my **config.xml** too. can you please help why code is not working ?

In my device ready function and button click event :

```
cordova.plugins.email.open({
            to: '',
            subject: 'test subject',
            body:'',
            isHTML: false
        });
```

my **index.html** code :

```
<script type="text/javascript" src="js/jspdf.min.js"></script>
<script type="text/javascript" src="js/email_composer.js"></script>
```

**Comment by dileeppdkr** [comment]
I am also facing same issue. Any updates on this @Priyansh ?

**Comment by Priyansh** [comment]
I still had no luck till this date @dileeppdkr , keep trying to figure it out. If you resolve this , feel free to share info

**Comment by hrpatidar** [comment]
Hi All,

I am facing the same kind of issue. Plugin is not able to open any Email client. I have done plugin installation using cordova commands. That is:
cordova plugin add https://github.com/katzer/cordova-plugin-email-composer.git

After that in my controller i have checked '**isAvailable**' method. It is always coming **false**. 
cordova.plugins.email.isAvailable(
    function (isAvailable) {
        alert(isAvailable)
    }

Then after I called for draft email. That is : 
cordova.plugins.email.open();

But is not opening any email client. Please help me out. 

Thanks

**Comment by ramkumarkr** [comment]
Using version 0.8.2 solved the issue for me

**Comment by seopei** [comment]
PR #245 will fix this
sdk's >= 23 need runtime permissions

**Comment by Priyansh** [comment]
Any updates guys, how to resolve this issue?

**Comment by aspcsharp9** [comment]
Any solution for this problem, why don't open email client?

**Comment by aspcsharp9** [comment]
For all Uninstall version 0.8.3 and install 0.8.2 work fine for android.....

**Comment by LebToki** [comment]
how do u install a 0.8.2 ?
from a local folder ?
installing it from a Git Pull request is unsuccessful for some reason

Fetching plugin "cordova-plugin-email-composer@0.8.2" via npm
Error: Failed to fetch plugin cordova-plugin-email-composer@0.8.2 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: version not found: cordova-plugin-email-composer@0.8.2

**Comment by LebToki** [comment]
function sendEmail(to, subject, body) {
			try {
				return $cordovaEmailComposer.isAvailable().then(function() {
					var email = {
						to: to,
						subject: subject,
						body: body
					};

					$cordovaEmailComposer.open(email);
				});
			} catch (e) {
				return $q.reject('$cordovaEmailComposer is not available or failed. Are you running the app within a browser?');
			}
		}
//	
	}

**Comment by lfreneda** [comment]
same here, tips?

**Comment by LebToki** [comment]
Nothing, tried everything you could imagine!

**Comment by lfreneda** [comment]
@LebToki use this fork: https://github.com/hypery2k/cordova-email-plugin 

is working for me :dancer:

**Comment by lfreneda** [comment]
@Priyansh use this fork: https://github.com/hypery2k/cordova-email-plugin

**Comment by LebToki** [comment]
trying now!
Hope it works :)

**Comment by hoongoon86** [comment]
#245 Fixed this issue, Thank you!

**Comment by katzer** [comment]
I've made various code updates, especially for Android. Also parts of the PR have been integrated.

**Comment by katzer** [comment]
Please reopen if its still a topic with latest updates
