### ISSUE TITLE
Access local image in HTML body of email

### ISSUE THREAD

**Issue by wkwyatt** [katzer/cordova-plugin-email-composer#244]
`var email = {
    subject     : 'Title',
    body        : '<img src="images/logo.png">',
    attachments   : 'file://images/logo.png',
    isHtml      : true
};`

I have already tried this also: `<img src="relative://images/logo.png>`

The image is not showing up in the body

**Comment by garima-goyal** [comment]
hello,
I have the same issue,
when sending the image as html, the  image is showing up as an object.
Please help asap
Thank you in advance

**Comment by katzer** [comment]
It depend on the mail client if he supports images. The plugin takes care the your attachments. However it does not parse nor manipulate file URLs within the body. I don't think that on Android for example it will work. Because the invoked app does not know where to find such file.
