### ISSUE TITLE
Email client is crashed in ios10.

### ISSUE THREAD

**Issue by prasadyallapu** [katzer/cordova-plugin-email-composer#246]
Hey @katzer  currently we are adding a email plugin to our app.I am using following cordova plugin [https://github.com/katzer/cordova-plugin-email-composer.git].We are testing the app in ionic view ios ipad with (version 10.0.2).

Problem: To use email we wrote a click function to open email plugin,when clicking the button the ionic view is closing.

Note:

Removed and added cordova plugins multiple times it didnt worked.
Added meta http-equiv="Content-Security-Policy" content="default-src *; script-src 'self' 'unsafe-inline' 'unsafe-eval' ; style-src 'self' 'unsafe-inline' " came to know that safari had more restrictions in new version(ios10).
Current ionic version using in my development is 1.7.7
It will helpful if you suggest if I am missing any?

My system information:

Cordova CLI: 5.4.0
Gulp version: CLI version 3.9.1
Gulp local:
Ionic Version: 0.9.27
Ionic CLI Version: 1.7.7
Ionic App Lib Version: 0.6.3
OS: Windows 8.1
Node Version: v4.2.1

**Comment by orhankutlu** [comment]
@prasadyallapu You got any update? I am planning to use this plugin

**Comment by prasadyallapu** [comment]
@orhankutlu I am using social share plugin it working so far with you any issue.But with cordova social share plugin I am unable to do attachments.I am able to send the mail with.

Please try it out.
**Name of the plugin** -  cordova-plugin-x-socialsharing

Please let me know if attachments is working while you are using above plugin.

**Comment by orhankutlu** [comment]
@prasadyallapu I don't wanna use socailsharing plugin :) So couldnt you send any email with this plugin? Or you got some problems with attachment? I just need to send text emails only

**Comment by prasadyallapu** [comment]
@orhankutlu I am able to send mail with is plugin.

.Check this function **(window.plugins.socialsharing.shareViaEmail**) in plugin you will get it.Using this email we should be able to trigger directly.I think this and cordova mail plugin behavior is same as far I know.

Any reason you don't want to use social share plugin?

**Comment by orhankutlu** [comment]
@prasadyallapu No reason on my end. Project lead doesnt want :D

**Comment by katzer** [comment]
Whats the crash log and the sample code to reproduce?

I've tested with iOS@9 and iOS@10 and it works so far.

**Comment by katzer** [comment]
Please reopen if its still a topic with latest updates

**Comment by husainkhan** [comment]
All issue here do not lead to any possible solution. I can't understand why these people are in a hurry to close the issue without checking whether the previous issue is resolved or not.
