### ISSUE TITLE
Html link is not working in gmail

### ISSUE THREAD

**Issue by surajkhanal** [katzer/cordova-plugin-email-composer#247]
As in the documentation, i have tried with the body:'<a href="http://link"'>Download</a>' . But gmail only shows the text .I also try to work with html instead of body but it also doesn't work.

**Comment by jasminpethani** [comment]
I also facing the same issue but i is working fine with Gmail Version 6.10 but with 6.11 it's just showing text instead of html link

**Comment by surajkhanal** [comment]
Finally i found that the latest gmail version is not supporting any hyperlink and html styling. There is no such issue with the email composer .

**Comment by chrlvclaudiu** [comment]
Regarding the link issue the only solution for me so far was the answer from SO: http://stackoverflow.com/questions/14560717/android-action-send-hyperlink-not-working-in-gmail
that is, the <a> href attribute's value has to be the same with the link title. 

That's acceptable for me, but no solution for the styling yet :(
