### ISSUE TITLE
This plugin killed my app!

### ISSUE THREAD

**Issue by edtiley** [katzer/cordova-plugin-email-composer#250]
Just an FYI Over the weekend I added the email-composer plugin to an app I'm building in the Intel XDK.

When I added the plugin, all the (previously working) javascript stopped working. I put an alert() as the first thing in the first function that runs and nothing, it just silently failed.

When I removed the plug in, my app immediately resumed working properly with no modifications to the code.

I'm attaching a screenshot of the other plugins loaded in the app so you have an idea of the environment.

Good luck with it. Figuring this issue out is WAY above my pay grade.

Thanks,

Ed
![plugins](https://cloud.githubusercontent.com/assets/22566235/21652972/fbcd345c-d27c-11e6-9913-6f8543da219e.jpg)

**Comment by WuglyakBolgoink** [comment]
Hi @edtiley ,

we need Logs  📟  to know what was happened 👨‍⚕️

**Comment by edtiley** [comment]
Sorry. I left the message and a list of the other plugins that were  on the 
machine, and I moved on. No logs, no real recollection of the facts. Ended 
up using the social networking plugin.

Ed

-----Original Message-----

**Comment by katzer** [comment]
@Need logs, I can't reproduce with the sample app.
