### ISSUE TITLE
HTML tags problem

### ISSUE THREAD

**Issue by Sejushi** [katzer/cordova-plugin-email-composer#251]
Hi, i used your plugin but i have big problem with html tags.
I need to use it but when i try, i get text without html. Of course i use "isHtml" parameter. My Android SDK version is 23 and i use application com.android.email. What i can to do to use it?

**Comment by zabojad** [comment]
Same issue here on Android... And I've checked the allowed tags [there](https://github.com/katzer/cordova-plugin-email-composer#html-and-css-on-android) first. Any idea ?

**Comment by zabojad** [comment]
@Sejushi did you find a solution ?

**Comment by Pigsnuck** [comment]
Any news here? I also have this problem and cannot find a workaround.

**Comment by katzer** [comment]
https://github.com/katzer/cordova-plugin-email-composer#html-and-css-on-android
