### ISSUE TITLE
Latest works on iOS but not Android

### ISSUE THREAD

**Issue by abouttimeruss** [katzer/cordova-plugin-email-composer#254]
I've had the issue where on Android, it doesn't bring up the email, so I revert back to 0.8.2 and that works, but won't build on the latest iOS ionic/cordova. I can install the latest or 0.8.3 and it works great on iOS but doesn't have the fix for the email to come up on Android. I need one that works for both. Any ideas?

**Comment by pfFredd** [comment]
Same issue here. 0.8.3 works fine for iOS but nothing happens on Android. 0.8.2 on the other hand causes build problems so downgrading isn't that good of an option.

**Comment by trekiteasy** [comment]
Same issue here : on some Android devices (ex: Asus Zen Pad 10), the email options doesn't show up.

**Comment by michaelhodgins** [comment]
Same here. I've switched to using a `mailto:` link. It's not great, but it works.

**Comment by skicson** [comment]
I'm guessing this issue is caused by a bug in Cordova as noted [here](https://issues.apache.org/jira/browse/CB-12424).   The plugin tries to send back a multipart response on the `isAvailable` function which fails.  Updating the  NativeToJSMessageQueue.java file seems to fix the problem.

**Comment by Jun711** [comment]
This fork works
[hypery2k](https://github.com/hypery2k/cordova-email-plugin/tree/greenkeeper/conventional-changelog-cli-1.3.1)

**Comment by rajatkhare619** [comment]
Thanks @Jun711 , it worked!

**Comment by sadiq-mc** [comment]
Thanks @Jun711 ....

**Comment by carlo318** [comment]
For me worked as well.
Thanx @Jun711 !

**Comment by laberg** [comment]
Thanks @Jun711 , email client now shows even if no email account is configured.

**Comment by katzer** [comment]
Please give a try to the recent updates.

**Comment by katzer** [comment]
Please reopen if its still a topic with latest updates

**Comment by D-Marc1** [comment]
I'm still getting this issue with the latest version of this plugin via NPM on Android 7.0, but not iOS. I get this message on Chrome `Cannot read property 'open' of undefined`.
