### ISSUE TITLE
iOS build error: Cordova/NSData+Base64.h file not found

### ISSUE THREAD

**Issue by pat-flew** [katzer/cordova-plugin-email-composer#257]
Hi,

From today (build was working yesterday), I am getting this issue when building for IOS: #166 

If I install release 0.8.3 instead, the issue does not happen.

Using cordova 6.5.0.

**Comment by Ramprasathselvam** [comment]
Refer this Link
https://stackoverflow.com/questions/36348202/cordova-4-0-1-cdv-camera-cordova-nsdatabase64-h-not-found/52606879#52606879
