### ISSUE TITLE
Callback returns "OK" all the time

### ISSUE THREAD

**Issue by vogloblinsky** [katzer/cordova-plugin-email-composer#258]
Plugin version : 0.8.4
Cordova : 6.5.0
Ubuntu 16.04

After launching email app with `.open({}, function(cbStatus){})`, `cbStatus` is always equal to 'OK'

If the user close the email window, the callback should says 'KO', saying window was dismissed or email not sended.

Here is the scenario :

![screenshot_20170609-142950](https://user-images.githubusercontent.com/2841805/26975538-88c941de-4d20-11e7-92bb-9929f6cc0bda.jpg)

![20170609_143138](https://user-images.githubusercontent.com/2841805/26975549-927e769a-4d20-11e7-97b9-3a54a6e7c047.png)

![screenshot_20170609-143034](https://user-images.githubusercontent.com/2841805/26975543-8c7b872e-4d20-11e7-99a5-2dc2ecb2db76.png)

**Comment by katzer** [comment]
@vogloblinsky Unfortunately what you're looking for is not supported by most platforms. Only iOS gives such info back to the caller. Not Android, Windows,... Thats why its not included at all.

**Comment by vogloblinsky** [comment]
@katzer thanks for the information. I will work with that limitation.
I close the issue.
