### ISSUE TITLE
Android 4.4.4 - ES6 method in js file error

### ISSUE THREAD

**Issue by vogloblinsky** [katzer/cordova-plugin-email-composer#259]
Specific call to an ES6 function failed in Android 4.4.4 without Crosswalk

```Uncaught TypeError: Object mozilla/5.0 (linux; android 4.4.4; samsung galaxy s5 - 4.4.4 - api 19 - 1080x1920 build/ktu84p) applewebkit/537.36 (khtml, like gecko) version/4.0 chrome/33.0.0.0 mobile safari/537.36 has no method 'includes' plugins/cordova-plugin-email-composer/www/email_composer.js:23```

**Comment by katzer** [comment]
@vogloblinsky Please upgrade to the latest version.
See https://github.com/katzer/cordova-plugin-email-composer/blob/master/CHANGELOG.md#version-086-12062017

**Comment by vogloblinsky** [comment]
Thanks :+1:
