### ISSUE TITLE
Not able to see rich text in gmail client

### ISSUE THREAD

**Issue by sanvenkur** [katzer/cordova-plugin-email-composer#260]
Hi Team,

I tried the below code in my ionic v1 app for sending rich text in email. But its not working it showing me the plain text instead. even anchor tag not working in gmail client app.

```
var _html = '<!DOCTYPE html>'+
'<html>'+
'    <head></head>'+
'    <body>'+
'        <h2>John</h2>'+
'        <a href="https://www.google.com">Google</a>
'    </body>'+
'</html>';

cordova.plugins.email.open({
                to: 'a@a.com', // email addresses for TO field                
                subject: 'test mail', // subject of the email
                body: _html, // email body (for HTML, set isHtml to true)
                isHtml: true, // indicats if the body is HTML or plain text
            }, function (result) {
                console.log('result', result);
            });              
```
What i have observed is only `<p>` and `<br>` tags are working
Could you please tell me why other tags are not working? especially `<a>` tag.

**Comment by katzer** [comment]
@sanvenkur See https://github.com/katzer/cordova-plugin-email-composer#html-and-css-on-android

Try:

```js
'<h2>John</h2>'+
'<a href="https://www.google.com">Google</a>'
```

**Comment by sanvenkur** [comment]
@katzer Thanks for the reply. But it did not work I tried as below.

```
var _html = '<h2>John</h2>'+
'<a href="https://www.google.com">Google</a>';

cordova.plugins.email.open({
    to: 'a@a.com', // email addresses for TO field                
    subject: 'test mail', // subject of the email
    body: _html, // email body (for HTML, set isHtml to true)
    isHtml: true, // indicats if the body is HTML or plain text
}, function (result) {
    console.log('result', result);
}); 
```
I am using gmail client app version 7.6.4.158567011.release.

Please find the attached screenshot of the gmail app
![screen shot 2017-07-04 at 12 07 20 pm](https://user-images.githubusercontent.com/2735435/27818017-86f42b54-60b1-11e7-8fc7-9c262a5b2018.png)

**Comment by katzer** [comment]
@sanvenkur As the client only shows the innerHTML content, its a limitation for Gmail or a Gmail setting.

**Comment by sanvenkur** [comment]
@katzer oh.. ok. Will try. Thank you.

**Comment by captainjim1** [comment]
So were you able to get any kind of formatting into your Android email client? Even though the documentation here says it's possible to send html or rich-text, nothing works. I don't understand why the devs claim it works when it clearly doesn't for Android.

**Comment by dkarandi** [comment]
I am facing the same issue. If anybody found any solution to this, please let me know. Thanks!

**Comment by katzer** [comment]
@captainjim1 If you follow the README you will read that its not possible anymore since KitKat and|or Gmail app v6.x
