### ISSUE TITLE
Send email in background

### ISSUE THREAD

**Issue by rasti9** [katzer/cordova-plugin-email-composer#261]
Does this plugin support sending emails in background?

**Comment by markdon** [comment]
I highly doubt it. It utilizes the mail apps installed on the phone. 

You would have to do [something like this](https://stackoverflow.com/questions/2020088/sending-email-in-android-using-javamail-api-without-using-the-default-built-in-a), as an example for Android.

**Comment by katzer** [comment]
@rasti9 No it doesn't
