### ISSUE TITLE
Documentation is out of date regarding Android and HTML

### ISSUE THREAD

**Issue by captainjim1** [katzer/cordova-plugin-email-composer#264]
Many people , myself included, are led to believe that this plugin allows sending HTML/RichText emails on Android - specifically in the native Gmail app. It appears this is no longer the case. Even the limited subset of tags listed fail to work on most Android email applications.

**Comment by katzer** [comment]
@captainjim1 I tried some things and it seems like its not working anymore since KitKat maybe.

You wrote that it fails to work on most Android email apps. What are the working clients?

**Comment by samnova** [comment]
Seems it stopped working with gmail at version 6.x, previous versions worked fine.

https://stackoverflow.com/questions/41123912/send-html-email-with-gmail-6-11-6-using-intent

**Comment by captainjim1** [comment]
@katzer - I haven't found a working email client.. I tried Gmail and Yahoo! mail. I hesitated to say ALL clients, because I don't know if it's ALL of them. Thanks!

**Comment by katzer** [comment]
I've updated the README. Hopefully there will be a better support for it in the future like a real email API.
