### ISSUE TITLE
import17 is not defined

### ISSUE THREAD

**Issue by akshatbhargava123** [katzer/cordova-plugin-email-composer#266]
Whenever I try to use this plugin in my ionic project, the app doesn't load and chrome debugging console shows import17 is not defined.
Please help, thanks.

**Comment by katzer** [comment]
@akshatbhargava123 Are there any other debug infos? "import17" says nothing to me...

**Comment by akshatbhargava123** [comment]
@katzer Sorry sir, but whenever I install this plugin to my app, app stops executing when apk is build and error says import17 is not defined. :( Please help.

**Comment by katzer** [comment]
@akshatbhargava123 I guess that the reason is the Ionic wrapper for this plugin. It's not the plugin itself.
