### ISSUE TITLE
App crash with attachements containing brackets in the filename

### ISSUE THREAD

**Issue by bedis-elacheche** [katzer/cordova-plugin-email-composer#267]
On iOS, if you try to attach a file containing brackets the **setAttachments** method raises an exception and rhe app crashes.

Example:

Filename: "file:///var/mobile/Containers/Data/Application/xxxxxx/Documents/filename.pdf"
=> No problem

Filename: "file:///var/mobile/Containers/Data/Application/xxxxxx/Documents/[ filename ].pdf"
=> App crashes

**Comment by katzer** [comment]
@bedis-elacheche Please post a crash log?

**Comment by bedis-elacheche** [comment]
@katzer sadly I can't do that since I don't currently have an access to an iDevice :/
