### ISSUE TITLE
html in body with isHtml: true not working

### ISSUE THREAD

**Issue by sergerot** [katzer/cordova-plugin-email-composer#268]
Gmail as choosen client does not handle html in body! 

Example:
...
body: '\<h2>abc\</h2>',
isHtml: true

**Comment by captainjim1** [comment]
Read the info on the main page -- html email is no longer supported BY GOOGLE on Android devices - there's nothing we can do about it.

**Comment by katzer** [comment]
See https://github.com/katzer/cordova-plugin-email-composer#html-and-css-on-android

**Comment by sergerot** [comment]
Oh. Thank you and sorry:). I spend very long time to include html in my body yesterday... It was very frustrated:/. Now i know the reason. Thx:).
