### ISSUE TITLE
How to send a script

### ISSUE THREAD

**Issue by pntagl** [katzer/cordova-plugin-email-composer#271]
I Want send a webform script something like
`<script src="abcd.js"><script>
 <script>
  //Some functions
</script>
`

It only sends the   //Some functions part , not entire code,  any suggestion..?

**Comment by katzer** [comment]
@pntagl I am not sure about what you are expecting. You cannot embed JS code into the email body. If the mail client doesn't allow to do, then it's not possible.

**Comment by pntagl** [comment]
Thanks Katzer! for your quick response, actually I need this functionality for my app can you suggest me how to achieve it.

**Comment by katzer** [comment]
@pntagl Usually email clients block JavaScript code for good reason.
