### ISSUE TITLE
Header is shifted up after opening the email client

### ISSUE THREAD

**Issue by jvhe123** [katzer/cordova-plugin-email-composer#274]
I use this plugin in an Ionic1 app (ios). 

After the emailclient is closed, the header of my app is shifted up. This means that half of the header is behind the iOS-toolbar (with battery percentage, hour, wifi signal, ....).

![img_8025](https://user-images.githubusercontent.com/21331193/31989826-b5070fdc-b973-11e7-8eae-4af04ee937c3.jpg)

How could I solve this problem ?

**Comment by katzer** [comment]
@jvhe123 You may try out https://github.com/katzer/cordova-plugin-hidden-statusbar-overlay

**Comment by jvhe123** [comment]
HiI don't understand how this will solve my problem. The problem with the header which is shifted up, only occurs after I call the email-composer plugin.  So clearly this plugin does something in order to shift the header upwards.To reproduce on iOS :- run ionic1 app with a ion-header-bar : header is shown correctly- call the email-composer plugin -> email client is opened- close the email client -> the header of the ionic-app is suddenly shifted upwards.I hope you could give me some more detailled instructions.Thank you.Kind regards  Joost-----Sebastián Katzer <notifications@github.com> schreef: -----Aan: katzer/cordova-plugin-email-composer <cordova-plugin-email-composer@noreply.github.com>Van: Sebastián Katzer <notifications@github.com>Datum: 29-10-2017 10:41Cc: jvhe123 <jvhe@axi.be>, Mention <mention@noreply.github.com>Onderwerp: Re: [katzer/cordova-plugin-email-composer] Header is shifted up after opening the email client (#274)@jvhe123 You may try out https://github.com/katzer/cordova-plugin-hidden-statusbar-overlay

**Comment by katzer** [comment]
@jvhe123 Your issue is related to ionic or maybe how the HTML viewport is configured.

Maybe that helps: https://github.com/ionic-team/ionic/issues/932
