### ISSUE TITLE
Use email-composer as a email viewer

### ISSUE THREAD

**Issue by nareshbhatia** [katzer/cordova-plugin-email-composer#275]
Just came across this plugin. I have a requirement to view emails downloaded into the application's dataDirectory. Can email-composer open local files and display them? If yes, what is the API for this and what formats does it support (.eml, .msg)? Will I be able to open the attachments (in-app or using the default app for the attachments)?

BTW, to add attachments to an email, is there a recommended file chooser plugin that works with iOS?

Thanks in advance.

**Comment by katzer** [comment]
@nareshbhatia You can use the plugin as described in the README. The email-composer is not an read-only email viewer for .eml files.

There are several file-picker plugins. The composer view also allows to choose files.

**Comment by nareshbhatia** [comment]
@katzer, thanks for your response. I need a quick clarification. You mentioned:

> The email-composer is not an read-only email viewer for .eml files.

It's ok if the view is read-write - "read-only viewer" is not a hard requirement. So the question boils down to: does composer understand MIME formatted messages? If I take care of picking and loading .eml files and hand over the content to email composer, will it be able to display them?

**Comment by katzer** [comment]
> does composer understand MIME formatted messages?

No

> If I take care of picking and loading .eml files and hand over the content to email composer, will it be able to display them?

Yes

**Comment by nareshbhatia** [comment]
@katzer, thanks for the quick response. I will give it a try.

**Comment by nareshbhatia** [comment]
@katzer, starting to play with the plugin now. I am able to bring up composer view using `cordova.plugins.email.open(...)`.

You mentioned that

> The composer view also allows to choose files

I did not find a way to do this in the UI. Can you please clarify?
