### ISSUE TITLE
Prevent request for permission to access Contacts on Android

### ISSUE THREAD

**Issue by mdublin** [katzer/cordova-plugin-email-composer#277]
Using the current version of this plugin for an Android build and it looks like it may be the cause of users being prompted to grant access to Contacts (could be wrong). Is that something we can suppress? Will the plugin work normally without access to Contacts?

**Comment by fabiusss** [comment]
I could not run the plugin but I resolved commenting **emailComposer.isAvailable()**
`
// this.emailComposer.isAvailable().then((available: boolean) =>{
//   if(available) {
         let email = {
          to: value,
          subject: 'Richiesta informazioni'
        };
        this.emailComposer.open(email);
// });
//}
`

**Comment by mdublin** [comment]
@fabiusss Thanks for the suggestion, what if I need to check for availability though? Maybe there's no way of being able to check `$cordovaEmailComposer.isAvailable()` without triggering this permissions request on Android?

**Comment by katzer** [comment]
The plugin asks for permission to access the list of (email) accounts. Without that permission the `isAvailable` function cannot return useful value.

> Maybe there's no way of being able to check $cordovaEmailComposer.isAvailable() without triggering this permissions request on Android?

That could be done. However if it doesn't matter if its available or not, why you don't just call `open`?

**Comment by jwburnside** [comment]
@katzer I think it is because the open() function does not have a result callback to handle cases where a user does not have a default email client configured. The function will just do nothing, and a developer cannot alert the user of an appropriate action to take, like installing an email client.
