### ISSUE TITLE
Plugin versions  not listed in Readme

### ISSUE THREAD

**Issue by bot101** [katzer/cordova-plugin-email-composer#278]
I am at a loss at which version of the plugin to use as the one i installed with the command `cordova plugin add cordova-plugin-email-composer` says `Plugin doesn't support this project's cordova-android version. cordova-android: 6.1.2, failed version requirement: >=6.2.0`. I am trying to install an older version that should work (I think so), but don't know which version number to use with `cordova plugin add cordova-plugin-email-composer@VERSION` since its not listed and i do not want to update cordova-android at this time.

**Comment by markdon** [comment]
Just looking back at history of package.json it looks like the cordova-android: >=6.2.0 requirement was added in [0.8.4](https://github.com/katzer/cordova-plugin-email-composer/blob/711699d27d77fe28f618aaa62d3db99cce75b257/package.json). 

[0.8.3 doesn't have it](https://github.com/katzer/cordova-plugin-email-composer/blob/5b6189ed89e36ba2239715e3bb4bc8d0e5220ebe/package.json). Maybe give that a go.

**Comment by katzer** [comment]
@bot101 Prior to cordova-android 6.2 multipart messages were broken. With cordova-android 6.1 you need this commit: bd337a2a425b612466373897a7e544d67bb72452
