### ISSUE TITLE
Plugin works in Android 4 but not in Android 6

### ISSUE THREAD

**Issue by bicimapas** [katzer/cordova-plugin-email-composer#280]
Hello

I have an app built with phonegap build and use a plugin forked from this one. There is no an Issues tab on the Github page for that plugin, so I wonder whether this is the correct place to ask.

The plugin is installed using 

`<gap:plugin name="cordova-plugin-email-composer" version="0.8.3" source="npm" />`

and I am testing in 2 devices, one with Android 4.1.2 where it works well and the second with Android 6 and does not work.

Are there any settings I should add for it to work on Android 6?

Thank you

**Comment by WalMast** [comment]
Some details of any errors would be useful. Just saying "Does not work" provides no value whatsoever.

**Comment by bicimapas** [comment]
Thanks for the reply.

I have a button that triggers a function to send an email. The funtion is: 

`function sendEmail(){
	cordova.plugins.email.open();
		}`


and the button is:

`<button  onclick ='sendEmail()'>Send Email</button>`


In the confix.xml I call the plugin for phonegap build as shown in my first post above.

and I make sure the plugin is working using this:

`<script>document.addEventListener('deviceready', function () {
	// cordova.plugins.email is now available
			}, false);	</script>	  `

When I run this in the device with Android 4.1.2 and click the Send Email Button, a window asking for what account to use is opened and the email can be composed and sent with the selected account. When I run it in the  Android 6 device, nothing happens. The Send Email button gets highlighted but the function to send the email is not triggered. No error messages are shown. Permissions to access the accounts are set to allow.

any ideas of what should be added for it to work on Android 6? 

Thanks

**Comment by katzer** [comment]
@bicimapas You use a version of the plugin that is old already and not fully compatible anymore with recent versions of cordova and platforms.

**Comment by bicimapas** [comment]
Thank you. What is the lastest Phonegap build compatible versión that I shall use?

**Comment by katzer** [comment]
The latest version is v0.8.11

**Comment by bicimapas** [comment]
My apologies for taking so long to reply. The plugin is now working well, thank you
