### ISSUE TITLE
How to set up email service capability on iOS

### ISSUE THREAD

**Issue by nareshbhatia** [katzer/cordova-plugin-email-composer#282]
I am trying out this plugin on iOS - on a real device. `cordova.plugins.email.isAvailable(function (hasAccount) {}` returns `false`. How do I set up the device to be email capable. I have both gmail and outlook apps on the device which can successfully send/receive emails.

**Comment by nareshbhatia** [comment]
Figured it out. I did not have any account set up in Apple's Email app. As soon as I set up an account in there `hasAccount` is now true. Surprisingly `hasGmail` is still false. Don't know what it takes to make it true!

**Comment by escaroda** [comment]
Gmail app doesn't work for me too.
Tried "gmail" and "googlemail".. doesn't work
