### ISSUE TITLE
Apache Cordova 6.5

### ISSUE THREAD

**Issue by VPantaleo** [katzer/cordova-plugin-email-composer#284]
Hi, I've upgraded my App to apache cordova 6.5 and now it does not work
This is me config.xml

<preference name="phonegap-version" value="cli-6.5.0" />
  
  <preference name="permissions" value="none"/>
  <preference name="disable-push-notifications" value="1" /> 
  <preference name="orientation" value="default"/>
  <preference name="target-device" value="universal"/>
  <preference name="fullscreen" value="false"/>
  <preference name="webviewbounce" value="true"/>
  <preference name="prerendered-icon" value="true"/>
  <preference name="stay-in-webview" value="false"/>
  <preference name="ios-statusbarstyle" value="black-opaque"/>
  <preference name="detect-data-types" value="true"/>
  <preference name="exit-on-suspend" value="false"/>
  <preference name="show-splash-screen-spinner" value="true"/>
  <preference name="auto-hide-splash-screen" value="true"/>
  <preference name="disable-cursor" value="false"/>
  <preference name="EnableViewportScale" value="false"/>
  
  <preference name="android-minSdkVersion" value="14"/>
  <preference name="android-targetSdkVersion" value="22"/>
  <preference name="android-installLocation" value="auto"/>
  <preference name="SplashScreen" value="screen" />
  <preference name="SplashScreenDelay" value="5000" />
  
  <preference name="StatusBarOverlaysWebView" value="false"/>
  <preference name="InAppBrowserStorageEnabled" value="True" />
  <preference name="AndroidPersistentFileLocation" value="Compatibility" />
  <preference name="AndroidExtraFilesystems" value="files,files-external,documents,sdcard,cache,cache-external,root" />
  <preference name="iosExtraFilesystems" value="library,library-nosync,documents,documents-nosync,cache,bundle,root" />
  
  <plugin name="cordova-plugin-device" source="npm" />
  <plugin name="cordova-plugin-file" version="4.3.3" source="npm" />
  <plugin name="cordova-plugin-file-transfer" version="1.5.1" source="npm" />

  <plugin name="cordova-plugin-inappbrowser" source="npm" />
  <plugin name="cordova-plugin-splashscreen" source="npm" />
  <plugin name="cordova-plugin-statusbar" source="npm" />
  <plugin name="cordova-plugin-fileopener" source="npm" />
  <plugin name="cordova-plugin-uniquedeviceid" source="npm" />
  	
  <plugin name="cordova-plugin-email-composer" version="0.8.3" source="npm" />
  
  <plugin name="cordova-plugin-whitelist" source="npm" />
    <access origin="*" />
    <access origin="tel:*" launch-external="yes" />
    <access origin="mailto:*" launch-external="yes" />

	
	<access origin="http://*.google.com" />    
	<access origin="*" launch-external="yes" />
	
    <allow-intent href="http://*/*" />
    
    <allow-intent href="https://*/*" />
    
    <allow-intent href="tel:*" />
    
    <allow-intent href="sms:*" />
    
    <allow-intent href="mailto:*" />
    
    <allow-intent href="geo:*" />
    
    
	<allow-navigation href="http://*/*" />
	<allow-navigation href="https://*/*" />
	<allow-navigation href="data:*" />
    
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>

**Comment by katzer** [comment]
If that issue is related to the plugin, then please reopen and provide proper content. Thanks
