### ISSUE TITLE
iOS Gmail app doesn't get base64 attachment

### ISSUE THREAD

**Issue by escaroda** [katzer/cordova-plugin-email-composer#286]
Gmail app version 5.0.171217
Mailto works fine. 
Any ideas?

**Comment by katzer** [comment]
@escaroda The `mailto:` scheme uses the native mail framework is more advanced. Other apps like gmail handle the standardised [RFC 2368](https://www.ietf.org/rfc/rfc2368.txt) without support for MIME types or attachments.
