### ISSUE TITLE
BROWSER platform : Wrong value in CC

### ISSUE THREAD

**Issue by cedric2bx** [katzer/cordova-plugin-email-composer#287]
Setting only **'body'** property and then opening application such as Outlook results in wrong values in fields :
**&bcc** appears in  CC field 
![image](https://user-images.githubusercontent.com/35526067/35434329-1208bac6-0287-11e8-894c-0cb9aa5159c9.png)

After investigation it's because **cc**, **bcc** properties are arrays and not string.
So I suggest to correct **EmailComposerProxy.js** like this :

    if (Array.isArray(props.cc) && props.cc.length > 0) {
        options += '&cc=' + encodeURIComponent(props.cc.join(';'));
    }
    if (Array.isArray(props.bcc) && props.bcc.length > 0) {
        options += '&bcc=' + encodeURIComponent(props.bcc.join(';'));
    }

Note : You should do the same correction for **'to'** property

Thanks in advance

**Comment by cedric2bx** [comment]
Thanks for being reactive, but the fix is not enough

The problem is on the property checking
```
if (props.cc !== '') {
//stuff
}
```
because it's true with an empty array
It could be solved like this :
```
if (Array.isArray(props.cc) && props.cc.length > 0) {
//stuff
}
```

Thanks

**Comment by katzer** [comment]
I've updated the code. Now it looks to be fixed.

**Comment by cedric2bx** [comment]
Nice !!!
I am waiting for next release

**Comment by cedric2bx** [comment]
Already available ...

Thanks
