### ISSUE TITLE
Unexpected &bcc= in Cc field

### ISSUE THREAD

**Issue by swifmaneum** [katzer/cordova-plugin-email-composer#288]
Hi there! 

I'm facing an issue creating an Email like so via the Ionic native plugin:
```
let email = {
        to: 'john.doe@example.com',
        subject: 'Subject',
        body: 'Hi',
        isHtml: true
      };

this.emailComposer.isAvailable().then((available: boolean) => {
        this.emailComposer.open(email).then(() => {
          //Email opened
        })
      });
```

Creating the Email works fine and my mail client (Outlook) is opening up as I would expect. But there's an unexpected string (&bcc=) in the Cc field:
![bcc](https://user-images.githubusercontent.com/7429598/35575178-0b73560a-05dc-11e8-865d-07ab6b91689d.PNG)

I'm not really into the code but debugging into [EmailComposerProxy](https://github.com/katzer/cordova-plugin-email-composer/blob/master/src/browser/EmailComposerProxy.js#L59) I found that there's a check if `props.bcc !== ''`, which might be wrong as `props.bcc` is an array. Therefore `&bcc=` gets appended to options. Manually removing `&bcc=` from options solves the problem for me, so maybe that's the whole problem.

My plugin version is 0.8.13 and I'm testing on the browser platform.

**Comment by cedric2bx** [comment]
That's what I said (see issue 287 not fixed) #287 

In my last comment I suggest a solution

**Comment by swifmaneum** [comment]
You're right, it's a duplicate. I haven't seen your issue as it was already closed... Let's continue the discussion in the original issue. I'm closing this one.

**Comment by cedric2bx** [comment]
Could you or someone else re-open issue #287 ?
