### ISSUE TITLE
Composer not starting

### ISSUE THREAD

**Issue by mcdroemmel** [katzer/cordova-plugin-email-composer#289]
Hello 

Yesterday (1.2.2018) i made a new phonegap-build for ios with this plugin for ios. On my iPad  with iOS 10.3.3 the Mail-Editor Composer is no longer opening after calling open-Method.
The same code worked with one of my last builds in mid January.

Everything seems to be ok. Method isAvailable delivers true in Parameter hasAccount of Callback. Method hasPermission also delivers true in Parameter granted of Callback.

Because you made changes in the last day maybee this caused an issue on iOS?

kind regards
Matthias

**Comment by mcdroemmel** [comment]
Addition: 

Open Call is

`                cordova.plugins.email.hasPermission(function (granted) {
                    if (granted) {
                        cordova.plugins.email.open({
                            to: '',
                            cc: '',
                            subject: 'Montage/Service-Auftrag ' + actDataWI.WLDOC_POS,
                            body: 'Sehr geehte(r) ' + actDataWI.NAME1_WE,
                            attachments: b64AttData
                        });
                    }
                });
`

**Comment by mcdroemmel** [comment]
Addition:
0.8.13 works.

**Comment by veto-cearl** [comment]
+1

iOS Mail editor not launching with 0.8.14. Rollback to 0.8.13 works.

**Comment by dylanvdmerwe** [comment]
Same here, 0.8.13 works.

**Comment by katzer** [comment]
I will release a new version today. With 0.8.14 you have to specify `app:"mailto:"` manually as a workaround.
