### ISSUE TITLE
Error thrown with isAvailable on Google Pixel2, yet Open() works. 

### ISSUE THREAD

**Issue by viking2917** [katzer/cordova-plugin-email-composer#292]
Have been using the plugin successfully on many Android devices. I call isAvailable to confirm email client is available, then if so, call open(). This works fine.

Recently acquired a Google Pixel 2 and isAvailable is throwing some kind of error. I am using Ionic v1 and Ionic Native, it may be related to that. 

Steps to reproduce:

```
ionic start emailtest blank --type ionic1
cd emailtest
npm install ionic-angular@legacy
npm install ionic-native --save
npm install @ionic-native/core --save
ionic cordova plugin add cordova-plugin-email-composer; npm install --save @ionic-native/email-composer

```

Then find a copy of ionic-native.js per the ionic native install guide, copy it to your js directory, and include in your index.html file, e.g. 

`<script src="js/ionic.native.js"></script>
`

Then add ionic to your app.js, e.g: change

`.run(function($ionicPlatform) {
`

to

`.run(function($ionicPlatform, $cordovaEmailComposer) {
`

and add the following to your app.js

```
 $cordovaEmailComposer.isAvailable().then(
	  function() {
	      console.log("email available");
	      $cordovaEmailComposer.open({
		  to:      'max@mustermann.de',
		  cc:      'erika@mustermann.de',
		  bcc:     ['john@doe.com', 'jane@doe.com'],
		  subject: 'Greetings',
		  body:    'How are you? Nice greetings from Leipzig'
	      }).then(
		  function (msg) {
		      console.log('sent ', msg);
		  }, 
		  function (msg) {
		      console.log('nope ', msg); 
		  });
	  },
	  function () {
	      console.log("Error on isAvailable - email not available");
	  });

```

Then: 

```
ionic cordova platform add android
ionic cordova run android --device 

```

On a new Pixel 2, this will throw an error and trigger the "Error on isAvailable" console message. On a samsung s6 it works fine. 

Further, if you move the .open() call outside of isAvailable, and it will open the email client just fine (i.e. I do have an email account configured for the email client (in my case, gmail). 

The expected behavior would be for isAvailable to pass, or, open() should not work if isAvailable doesn't pass. 

(separately, the hasPermission() function doesn't seem to exist if you try to call it in the ionic-native manner - not sure if the ionic native wrapper doesn't expose it?) (e.g. $cordovaEmailComposer. hasPermission().then(....

I have attached the index.html, app.js and ionic-native.js files I used. 

[Archive.zip](https://github.com/katzer/cordova-plugin-email-composer/files/1776169/Archive.zip)

**Comment by katzer** [comment]
@viking2917 Please provide the whole stack trace.

**Comment by viking2917** [comment]
hi @katzer how do I get the stack trace? (to be clear my ionic app doesn't crash per se, it just throws an error, so I'm not sure exactly which stack trace would be called for... anyway if you can tell me how to get that info I will do so).

**Comment by welshcathy** [comment]
I have the same issue on Pixel 1, 8.1.
cordova-plugin-email-composer v0.8.15;
isAvailable() returns false, but calling open() directly works  just fine.

```
    let plugin = (<any>window).cordova.plugins.email;
    plugin.isAvailable((hasAccount: boolean) => {
      // hasAccount is false
    });
```

Here's my logcat from Android Studio starting just after call to isAvailable();
[pixel.log](https://github.com/katzer/cordova-plugin-email-composer/files/1821509/pixel.log)

**Comment by dematerializer** [comment]
The issue arises from a change introduced in API Level 26 (Android 8) where they decided that the GET_ACCOUNTS permission is no longer sufficient (see https://developer.android.com/about/versions/oreo/android-8.0-changes.html#aaad). As long as this plugin is not adapted to these new conditions, it is possible work around the issue by setting `<preference name="android-targetSdkVersion" value="25" />` your cordova config.xml.
