### ISSUE TITLE
Question:  Is it possible to send an attachment not embedded in email with ios

### ISSUE THREAD

**Issue by TobiasForster** [katzer/cordova-plugin-email-composer#293]
Hey,
is there any way to send an attachment (in my case, pictures) which is not embedded in email when sending with iOS mail app.
Use Case: take picture with camera, send it with mail application.

If I send my attachment with Android-mail the behaviour show as expected, the picture results as a mail attachment.

Is there any possibility to configure the desire behaviour for iOS, too?

Best regards,
Tobias Forster

**Comment by katzer** [comment]
No its only possible with iOS mail app.
