### ISSUE TITLE
Plugin asks for contacts access, compose might have wrong recipient

### ISSUE THREAD

**Issue by btxtiger** [katzer/cordova-plugin-email-composer#295]
In Android, the plugin asks for contacts access permission. I don't see why this is necessary because it should just open the email app(?).
Giving this permission leads to, that Android offers me to send the email to a different recipient than specified in the config object in my code! So if the user does not click "New Message", which is just one of 7 offered options, the target mail address will not be my intended for receiving feedback.

**Comment by svzi** [comment]
Why does this plugin even ask for contacts access? I would like to avoid having this permission request, just for sending a simple email. My users already start asking why I need that permission, I guess some believe every developer is evil and syncs there address book or something like that.

So I really want to get rid of this permission request. Any idea on how to do so?

**Comment by katzer** [comment]
In general you are right. The reason why its asking when calling the `isAvailable` function is to find out if you have configured an email account.

**Comment by svzi** [comment]
Thanks for the update, but is there anything I can do to avoid requesting that permission?

**Comment by katzer** [comment]
Since Android M the app only ask for permission at runtime. So simply dont use the `isAvailable` function.

**Comment by katzer** [comment]
Just call `open()`

**Comment by svzi** [comment]
Thanks, I've modified my code accordingly!

**Comment by katzer** [comment]
I will improve this situation with the next release (v0.9.0).

**Comment by svzi** [comment]
Great, thanks for letting us know!
