### ISSUE TITLE
Body is not set on Android 8.1 Microsoft Outlook App with isHtml: true

### ISSUE THREAD

**Issue by welshcathy** [katzer/cordova-plugin-email-composer#296]
"cordova-plugin-email-composer": "^0.8.15",
"@ionic-native/email-composer": "^4.5.3",
Android 8.1
Google Pixel 1

It all works perfectly on Android Google Mail, iOS Mail.
But on Android Outlook the body is never populated with isHtml true.
Only works with isHtml false.

logcat from execution of open();

[pixel outlook.log](https://github.com/katzer/cordova-plugin-email-composer/files/1821574/pixel.outlook.log)

**Comment by AndrWeisR** [comment]
Bug also confirmed on Android 6.0 with Outlook.

**Comment by katzer** [comment]
Most email clients for Android do not support HTML encoded output or just limited rich-text markup.
