### ISSUE TITLE
No attachment with cordova-android-platform and cordova-browser-platform 

### ISSUE THREAD

**Issue by ebeling** [katzer/cordova-plugin-email-composer#298]
I use this plugin in my ionic project ( version 0.8.15) with the following implementation:

`this.emailComposer.isAvailable().then((available: boolean) =>{
          //Now we know we can send
          let email = {
            attachments: ['base64:helloworld.csv//'+window.btoa('Hello world')],
            subject: 'xxxxxxxxxxxxx',
            body: 'How are you? Nice greetings .....',
          };
          // Send a text message using default options
          this.emailComposer.open(email);
      }).catch((reason => {
        alert(reason);
      }));`

Under cordova-ios-platform this works correctly, but with android platform (emulator with android 5.1.1 , android 6.0, android 7.0, real device with android 7.0) the email client opens with correct subject and body but without attachment. Same with cordova-browser-platform.

ionic info->
cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0
global packages:
    cordova (Cordova CLI) : 8.0.0 
local packages:
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 browser 5.0.3 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2
System:
    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 5.0.13 
    Node              : v6.11.3
    npm               : 5.7.1 
    OS                : macOS Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

**Comment by brunocollaco** [comment]
Ya, I'm also facing a similar problem and using version 0.8.15. I can't attach anything on gmail.

        let email = {
            to: 'collaco.bruno@gmail.com',
            cc: [],
            bcc: [],
            attachment: ['file:///storage/emulated/0/pedido.pdf'],
            subject: 'Heya',
            body: msg,
            isHtml: true,
            app: 'Gmail'
        }
        this.emailComposer.open(email);

I've tried also to downgrade all the way down to version 0.8.2 that I read on the issues it was working on android devices.

It does not attach anything: external files, assets imgs, nor base64.

cli packages: (/opt/nodeJS/lib/node_modules)
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0
global packages:
    cordova (Cordova CLI) : 7.0.1 
local packages:
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.9.2
System:
    Android SDK Tools : 26.1.1
    Node              : v6.9.4
    npm               : 3.10.10 
    OS                : Linux 4.9

**Comment by katzer** [comment]
Attachments do not work for browser platform.
