### ISSUE TITLE
Unable to attach base64 image as attachment in android. It crashes the app.

### ISSUE THREAD

**Issue by sabanad** [katzer/cordova-plugin-email-composer#300]
Hi, I'm unable to attach a base64 image as attachment in android. It crashes my app.

**Comment by TheDuc** [comment]
What email client are you using? Here it is working fine. Does your base64 string start with `base64:20180403_091616.jpg//` ? 20180403_091616.jpg is an example filename of course.

**Comment by filippopossenti** [comment]
Hi,
writing here just as a similar issue (only on a text file) was verified for a similar plugin (cordova-plugin-email) for my company's cordova app.
We verified that it happens on a Nexus 5X but doesn't on Samsung phones.
We haven't diagnosed the cause of the issue yet. Just though this might give a clue.

**Comment by scenekidsanta** [comment]
I am having the same issue on a Moto x4.  Anytime I try to use attachments it crashes instantly.  The base64 is valid.

**Comment by scenekidsanta** [comment]
I was having this issue as well and added the base64: filename.extension// before my actual base64 and that fixed it.  I also had to remove the "data:image/jpeg;base64" from by base64 string.  Once that was done it stopped crashing and works perfectly.

**Comment by katzer** [comment]
Please use it as described in the README.md Then it should work.
