### ISSUE TITLE
size of attachment

### ISSUE THREAD

**Issue by jfoclpf** [katzer/cordova-plugin-email-composer#301]
Hi, thanks for the great plugin :)

Is there any limitation to the size of the attachements?
it seems that when I attach just two big pictures (roughly 5 Mb each) it opens, it creates the email, but with no attachment.

I'm using Android and `cordova-plugin-email-composer 0.8.15 "EmailComposer"`

thanks

**Comment by katzer** [comment]
That depends on the email client,... The plugin has no size limit.
