### ISSUE TITLE
isAvailable function check unnecessary in android 5+?

### ISSUE THREAD

**Issue by Steven-Franwell** [katzer/cordova-plugin-email-composer#305]
There seems to be an issue where the `isAvailable` function returns an empty string "" in the `hasAccount` variable on android 5+. This was not an issue before I made the upgrade to android version 5.1.1. I was able to completely bypass the `isAvailable` call without ever receiving an error on android versions 5+. This was tested with no accounts setup on the phone and with existing accounts already setup.

I am not sure if versions before android 5 required this functionality as I have not tested earlier versions without it. However, 5.1.1 and 6.0.0 work fine without the call and allow for email setup/sending on multiple platforms (gmail, yahoo, and aol). 

There does seem to be one quirk where an attachment can sometimes be corrupted when first setting up an email, but after the email is setup, I was unable to replicate the issue.

**Comment by yechenchao** [comment]
Same here, I was using the plugin on ionic 4, `isAvailable` always return `undefined` value, took me a while to figure out why the email client didn't popup.

**Comment by katzer** [comment]
Dont rely to much on it. Even it returns false on Android it doesn't mean that its not possible. Its because Android doesn't provide an API for it and if the user doesn't make us the Android Mail or Google Mail the function might return false.
