### ISSUE TITLE
Not Working on Samsung Devices

### ISSUE THREAD

**Issue by ntclark4** [katzer/cordova-plugin-email-composer#307]
Testing on a Galaxy Note 9 with Android 8.1 and other modern Samsung phones.

When launching the composer, the share UI pops up but says, "**Open with** - All apps associated with this action have been turned off, blocked, or are not installed."

When I click on a hyperlink containing a mailto link, I get presented with share UI that says, "**Complete action using**," and then lists the three email apps I have installed. So it's almost like this plugin isn't even calling for the email composer on Samsung devices, and is trying to share in a different format.

**Comment by katzer** [comment]
@ntclark4 Is that still the case if you install the plugin directly from GitHub (latest dev version)? I cannot reproduce it

**Comment by ntclark4** [comment]
@katzer I no longer have a Samsung device to test with. We used a version of the plugin from around September/October, before you started making changes in November. Have there been changes since then that could have fixed it?

**Comment by katzer** [comment]
@ntclark4 I've a Samsung device but haven't experienced your issue. Yes I've made some changes regarding the share UI (chooser).
