### ISSUE TITLE
Not building on Cordova 6.3.1 and Cordova-android 5.2.1

### ISSUE THREAD

**Issue by remyar** [katzer/cordova-plugin-email-composer#310]
Hello,

I use Cordova 6.3.1 and Cordova-android 5.2.1 and Android SDK 21 but the plugin refuse to compil because , you force the SDK to 24+ an Cordova android >= 6.0.0

but, in Cordova 6.0.0 , the Cordova android is 5.0.0
it's a problem because the version doesn't correspond !!!

i modify in plugin.xml the version to Cordova Android >= 5.0.0 and remove the line with Framework 24+

And success , work like a charm in Android 8 and 6 !!!!

please update your plugin.xml for android to support it !!! ;-)

best regards

**Comment by katzer** [comment]
@remyar The plugin might work for older versions by some modifications. However I am not going to support a wide range of older platform versions.
