### ISSUE TITLE
Not working at IOS 12

### ISSUE THREAD

**Issue by josevi86** [katzer/cordova-plugin-email-composer#313]
Hello,

I have seen many problems about this, but the solution is not clear to me.

The add-on works perfectly with Android, but not with iOS. I've tried with two iphones, both have not installed gmail, only the pre-installed mail application. Is it mandatory to install another application? Or should the default mail application open?

Thank you.

**Comment by katzer** [comment]
Should work with (any) email client because the plugin uses the native email SDK interfaces.

**Comment by josevi86** [comment]
Im using Adobe Phonegap cli-8.0.0, not Cordova. Could be this a problem?

**Comment by auditctr** [comment]
I'm having the same issue on IOS 12.2.x,  there is no error,  it just executes the command but doesn't open the email client

**Comment by jfoclpf** [comment]
same error here

**Comment by jfoclpf** [comment]
it just executes the command and not output on the console

![image](https://user-images.githubusercontent.com/3984909/107863369-37f45600-6e54-11eb-89cb-d89e5134c867.png)

@katzer do we need to request any authorization on ios?
