### ISSUE TITLE
PWA : Can not attach PDF

### ISSUE THREAD

**Issue by troll-os** [katzer/cordova-plugin-email-composer#314]
Hello 

I'm using the plugin for a PWA, I'm getting my Blob object from a server and read it as a base64 string.

I tried several ways to get my base64 string, all outputing the same result, obviously (in case of that would have been it), and padded it to  "base64:mypdf//". 

I'm building my app with "ionic cordova build browser". The email application on desktop or mobile opens, but I can not get the attachment. 

I wanted to write the file on the device and then pass it to the attachments but it seems to be not working with the PWA approach.

I logged my email object and I can see the string correctly constructed. 
`attachments: ["base64:profil.pdf//JVBERi0xLjQKMSAwIG9iago8PAovVGl…vdCAyNyAwIFIKPj4Kc3RhcnR4cmVmCjQ0MTY1CiUlRU9GCg=="]`

**Comment by troll-os** [comment]
Here is my code
```
      var reader = new FileReader();

      let email = {
        to: '',
        attachments: [],
        subject: 'pdf',
        body: 'pdf.',
        isHtml: true
      };


      reader.readAsBinaryString(blob);
      reader.onloadend = function () {
        var pdf = reader.result;
        console.log(pdf);
        email.attachments.push('base64:profil.pdf//'+btoa(pdf));
        console.log(email);
        // Send a text message using default options
      };

      this.emailComposer.open(email);
```

**Comment by troll-os** [comment]
Just understood that onloadend is async... So the email object was not updated when sent to the app.

**Comment by darrensapalo** [comment]
Hi there.

I am using this plugin on the iOS platform and was able to use it successfully on the mobile device. What platform are you using?

At least for iOS mobile, it works (haven't tested on browser yet).

One difference we have for our processing is how we read our PDF. If you can [read your data as an ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsArrayBuffer), then you can [transform that ArrayBuffer into base64 data](https://stackoverflow.com/a/9458996/1323398).

This is what I did on my ionic project, and it worked. Let me know if that works for you.

**Comment by jfoclpf** [comment]
this should work in iOS as attachment

```js
cordova.plugins.email.open({
    subject:     'Cordova Icon',
    attachments: ['base64:icon.png//iVBORw0KGgoAAAANSUhEUgAAADwAAAA8CAYAAAA6...']
});
```

On my side it does work
