### ISSUE TITLE
Attachment can't be sent with outlook in windows app using email composer

### ISSUE THREAD

**Issue by mansi-arora-sofb** [katzer/cordova-plugin-email-composer#317]
I have used email composer plugin to send mail via windows app. The attachment is not being sent when using outlook. Though the same is working when build with IOS. Please help to resolve the issue.

**Comment by katzer** [comment]
Cannot reproduce... For me attachments using outlook does work.

**Comment by raghavendrav6** [comment]
I am using the 0.9.2 version. Facing the same issue. I am trying to attach a CSV file to the mail. 
It's working in different mail clients, except outlook. 

Kindly help to resolve this
