### ISSUE TITLE
Plugin crashes my app on Android Oreo

### ISSUE THREAD

**Issue by jondspa** [katzer/cordova-plugin-email-composer#326]
Thanks for this great plugin!

I'm having some trouble with Android Oreo.  Works fine on iOS.

I use version 0.8.2 since I mostly attach images with emails.  In Oreo, the plugin works fine for those emails without attachments,  When I try to attach a file to the email using the following (which works on iOS and works with other versions of Android), app crashes.

            cordova.plugins.email.open({
                to: [""],
                subject: message,
                isHtml: true,
                attachments: [newDataURL],
                body: string
            });

I've taken my Android app down for the moment.  I've tried 0.9.2 but no luck.  Any help would be greatly appreciated!

  Thanks,

     - Jon

**Comment by jondspa** [comment]
More information.

As dematerializer points out in a different issue:
The issue arises from a change introduced in API Level 26 (Android 8) where they decided that the GET_ACCOUNTS permission is no longer sufficient (see https://developer.android.com/about/versions/oreo/android-8.0-changes.html#aaad).

The problem now is that API Level 26 is required (since November 2018).

**Comment by DavidVc30** [comment]
Same issue here! Also on Oreo and also only when attaching a file (with the base64 string option) to an email....

Any help solving the issue would be greatly appreciated!

**Comment by DavidVc30** [comment]
I'm using PhoneGap as building platform.

Changing the plugin from "cordova-plugin-email" to latest version of plugin "cordova-plugin-email-composer"  solved the issue for me!

**Comment by jondspa** [comment]
Thanks DavidVc30!  I loaded the latest version (not 0.8.2) and also had to upgrade my android platform to 7.1.4 and now I can send emails with attachments in Oreo (and other versions of Android).

But I had my code wrapped in
   cordova.plugins.email.isAvailable

and this no longer works.  Have you had any luck with this?

Thanks much!
    - Jon

**Comment by DavidVc30** [comment]
You could try a combo of the hasAccount() and hasClient() methods mentionned on https://github.com/katzer/cordova-plugin-email-composer/blob/master/README.md

**Comment by jondspa** [comment]
Yes, that did the trick!  Thanks much.
