### ISSUE TITLE
de\appplant\cordova\emailcomposer\EmailComposer.java:121: error: local variable id is accessed from within inner class; needs to be declared final boolean res = impl.isAppInstalled(id);

### ISSUE THREAD

**Issue by bnolan001** [katzer/cordova-plugin-email-composer#328]
I'm building my app via the Ionic v4 CLI and seeing these errors for Android:
`...\java\de\appplant\cordova\emailcomposer\EmailComposer.java:121: error: local variable id is accessed from within inner class; needs to be declared final`
`                boolean res = impl.isAppInstalled(id);`
`                                                  ^`
`...\java\de\appplant\cordova\emailcomposer\EmailComposer.java:173: error: local variable props is accessed from within inner class; needs to be declared final`
`                    Intent draft = impl.getDraft(props);`

My config.xml has these settings for SDK
`    <preference name="android-minSdkVersion" value="21" />`
`    <preference name="android-targetSdkVersion" value="26" />`

Cordova Version:  8.1.2
Ionic Version:  4.12.0
Android Engine:  7.1.4

Installed Pluggins:
`cc.fovea.cordova.purchase 7.4.3 "Purchase"`
`cordova-admob 5.1.0 "AdMob Google Ads + Tappx"`
`cordova-android-support-gradle-release 2.0.1 "cordova-android-support-gradle-release"`
`cordova-clipboard 1.2.1 "Clipboard"`
`cordova-connectivity-monitor 1.2.2 "Connectivity Monitoring"`
`cordova-play-services-version-adapter 1.0.2 "Cordova/Ionic Google Play Services Versions Incompatibility Adapter"`
`cordova-plugin-android-permissions 1.0.0 "Permissions"`
`cordova-plugin-app-version 0.1.9 "AppVersion"`
`cordova-plugin-cocoapod-support 1.6.0 "Cordova CocoaPods Dependency Support"`
`cordova-plugin-device 2.0.2 "Device"`
`cordova-plugin-dialogs 2.0.1 "Notification"`
`cordova-plugin-email-composer 0.9.2 "EmailComposer"`
`cordova-plugin-flurryanalytics 1.4.6 "Flurry Analytics"`
`cordova-plugin-geolocation 4.0.1 "Geolocation"`
`cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"`
`cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"`
`cordova-plugin-ionic-webview 3.1.2 "cordova-plugin-ionic-webview"`
`cordova-plugin-splashscreen 5.0.2 "Splashscreen"`
`cordova-plugin-statusbar 2.4.2 "StatusBar"`
`cordova-plugin-whitelist 1.3.3 "Whitelist"`
`cordova-plugin-x-toast 2.7.2 "Toast"`
`cordova-sqlite-storage 3.2.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"`
`cordova.plugins.diagnostic 4.0.12 "Diagnostic"`
`uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"`

**Comment by dani-inside** [comment]
@katzer : Any chance to publish a new release which includes this bugfix?

**Comment by stevesum** [comment]
@katzer could you release a new version with these bugfixes? We use an automated build environment,  and we can't use only the released one from npmjs.
