### ISSUE TITLE
Cannot open MS Outlook on iOS

### ISSUE THREAD

**Issue by AndrWeisR** [katzer/cordova-plugin-email-composer#330]
I have the MS Outlook app installed on my iPhone. An Outlook account is set up, and the app sends and receives emails. I cannot open Outlook using this plugin though. I set app = "ms-outlook://compose" in my code when calling the open() function, but the Apple Mail app opens. Am I using the right value for app, or is there a bug?

**Comment by whodeee** [comment]
the value should be "outlook"

**Comment by tobikummer** [comment]
value "outlook" works fine, but attachments get lost...
