### ISSUE TITLE
Attachments get lost on iOS 13 and outlook

### ISSUE THREAD

**Issue by tobikummer** [katzer/cordova-plugin-email-composer#338]
Hi there
I use your plugin and all works fine. Our client now switched from "Apple Mail" to "Outlook" (all on iPad). I send emails with several pdf attached. If I change the App `app: 'outlook',` Outlook opens, the text, subject, ... all works, but the attachments get lost. 
My attachment-config looks 
`attachments: ["file:///var/mobile/Containers/Data/Application/2C701E6E-0975-4AA7-9C99-C0CF01BDA4DD/Library/NoCloud/assets/pdf/89/test1.pdf", "file:///var/mobile/Containers/Data/Application/2C701E6E-0975-4AA7-9C99-C0CF01BDA4DD/Library/NoCloud/assets/pdf/89/test2.pdf"]`
What am I doing wrong?

The error message is: The 'mailto' URI Scheme (RFC 2368) does not support attachments.

iOS version 13.0
plugin-version: 0.18.5 (tried it also with the latest version, same behavior)

**Comment by katzer** [comment]
Adding attachments only works with Apple Mail

**Comment by tobikummer** [comment]
okay, what a pitty 🙁

**Comment by jayaprasanth-g** [comment]
is there anyother way to open outlook with attachements?. Please suggest. same issue i'm having now.
