### ISSUE TITLE
Cannot use <img> element

### ISSUE THREAD

**Issue by ragcsalo** [katzer/cordova-plugin-email-composer#340]
I tried to insert an image from the web, but in the composer the place of the image was blank, and in the final email it shows a small [OBJ] box instead of the image. Can we insert images with a source from the web, or not? Also some other HTML tags (like FONT, H3 etc.) seem not to be working... (isHtml is set to true btw)

**Comment by jfoclpf** [comment]
Only the built-in email app for iOS does support HTML and CSS. Some Android clients support rich formatted text.
