### ISSUE TITLE
cannot get Email.open() method to work

### ISSUE THREAD

**Issue by BenieD** [katzer/cordova-plugin-email-composer#341]
Hello,

im trying to get this code to work on my android phone but when i try to run cordova.plugins.email.open() the error message is TypeError: Cannot read property 'email' of undefined.  

is anyone else having this issue?  any ideas how i can get it to work?
many thanks for your time
David

**Comment by jfoclpf** [comment]
sorry the very late reply

did you eventually solve the problem?

You can only use the plugin after `deviceready` is triggered 

```js
document.addEventListener('deviceready', function () {
    // cordova.plugins.email is now available
}, false);
```
