### ISSUE TITLE
How to add Line break to the email body ?

### ISSUE THREAD

**Issue by Thirus11** [katzer/cordova-plugin-email-composer#345]
Dear Katzer,

Can you help me on the below requirement
- I want to have gaps between the paragraphs while composing the mail body. I bringing the content from the backend(SAP - maintained in text module). The mail body is passed to a variable. We are Cordova-email-composer to send mail in the ipad. in the debug mode i am able to see the gaps between paragraphs. But whilöe sending mail in the ipad I am not able to see gaps.

cordova.plugins.email.open({
							subject: oPDFEMailModel.getProperty("/EmailSubject"),
							to: arrayEmail,
							cc: arrayCC,
							body: oPDFEMailModel.getProperty("/EmailMessage"),
							attachments: 'base64:attachment.pdf//' + base64
						});

**Comment by rmeske** [comment]
@Thirus11 ,

It depends on what platform you are building for.  The following handles, browser, Android, and iOS.
let lineBreak = this.common.isApp ? '<br>' : (this.platform.is('android') ? `%0D%0A%0D%0A` : `%0D%0A`);

**Comment by jfoclpf** [comment]
@rmeske `<br>` also works with android and iOS, I use it and it works
