### ISSUE TITLE
Newer version of plugin doesn't auto add GET_ACCOUNTS permission to Manifest

### ISSUE THREAD

**Issue by sardapv** [katzer/cordova-plugin-email-composer#349]
Older plugins like 0.8.15 used to add GET_ACCOUNTS permission automatically in manifest when plugin add command is run.
I spent hours finding why my app wasn't asking for permission. Found in older version it auto adds it. Please add it back

**Comment by regnete** [comment]
Add this to your config.xml to achive the 'old' behaviour:

```xml
 <platform name="android">
   <config-file target="app/src/main/AndroidManifest.xml" parent="/manifest">
            <uses-permission android:name="android.permission.GET_ACCOUNTS"/>
        </config-file>
 </platform name>
```
