### ISSUE TITLE
Error Error: 404 Not Found when compile cordova app

### ISSUE THREAD

**Issue by arielceb** [katzer/cordova-plugin-email-composer#352]
verbose node v12.18.3
verbose npm  v6.14.6
error code E404
error 404 Not Found - GET https://registry.npmjs.org/de.appplant.cordova.plugin.email-composer - Not found
error 404
error 404 'de.appplant.cordova.plugin.email-composer@0.8.2' is not in the npm registry.
error 404 You should bug the author to publish it (or use the name yourself!)
error 404 It was specified as a dependency of 'ManagerNetMovil'
error 404 Note that you can also install from a
error 404 tarball, folder, http url, or git url.
 verbose exit [ 1, true ]

**Comment by jfoclpf** [comment]
do you still have this problem?

**Comment by arielceb** [comment]
no, i haven't. Thanks
