### ISSUE TITLE
Application crush after try to open client

### ISSUE THREAD

**Issue by maxzirilli** [katzer/cordova-plugin-email-composer#361]
It's almost a pair of days that application crash when we try to open client.

Function HasClient also returns false; GMail is correctly installed;

We have Xiami phones and Android 11 installed

**Comment by asgeo1** [comment]
It's crashing for me too on Android.

```   
     java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.remove(ArrayList.java:503)
        at de.appplant.cordova.emailcomposer.Impl.getDraft(Impl.java:90)
        at de.appplant.cordova.emailcomposer.EmailComposer$4.run(EmailComposer.java:173)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

Seems to be an issue with this line of code: https://github.com/katzer/cordova-plugin-email-composer/blob/master/src/android/Impl.java#L90   removing an index that doesn't exist.

**Comment by Melf11** [comment]
same issue here

```E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: com.wkv.shippingcontrol, PID: 16457
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.remove(ArrayList.java:503)
        at de.appplant.cordova.emailcomposer.Impl.getDraft(Impl.java:90)
        at de.appplant.cordova.emailcomposer.EmailComposer$4.run(EmailComposer.java:173)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by linktap01** [comment]
Same issue here. Is there any fix yet?

**Comment by RolfDohrmann** [comment]
Same here. 

Device: Samsung A50
OS: Android 11
Context: Ionic/Angular/capacitor app

this.emailComposer.open(email);

Opening the mail client works on 2 devices:

Samsung S9+, Android 10
Samsung Tab A, Android 8.1

It crashes on 

Samsung A50, Android 11 

Android log:

E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-2
    Process: de.minidat.windat, PID: 22863
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.remove(ArrayList.java:503)
        at de.appplant.cordova.emailcomposer.Impl.getDraft(Impl.java:90)
        at de.appplant.cordova.emailcomposer.EmailComposer$4.run(EmailComposer.java:173)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

Any idea how to fix this? Is this specific to Android 11?

**Comment by linktap01** [comment]
Yes, the issue is specific to Android 11. I m still waiting for the issue :-(

**Comment by ashwin-dongare** [comment]
Hey, @katzer  Can you please look into this I am also having the same issue with the Android 11 app is crashing.
Thanks in advance!

**Comment by Euxiniar** [comment]
I'm a bit worried. This plugin seems abandoned

**Comment by Melf11** [comment]
looks like, but i can't really find an alternative... :-(

**Comment by Melf11** [comment]
A dirty fix is to just return getFilledEmailIntent(params) in getDraft(), but it works.

```
Intent getDraft (JSONObject params) {
   return getFilledEmailIntent(params);
}
```

**Comment by RolfDohrmann** [comment]
> A dirty fix is to just return getFilledEmailIntent(params) in getDraft(), but it works.
> 
> `Impl.java`
> 
> ```
> Intent getDraft (JSONObject params) {
>    return getFilledEmailIntent(params);
> }
> ```

Thanks a lot Melf11! Your fix works great!

**Comment by linktap01** [comment]
> A dirty fix is to just return getFilledEmailIntent(params) in getDraft(), but it works.
> 
> `Impl.java`
> 
> ```
> Intent getDraft (JSONObject params) {
>    return getFilledEmailIntent(params);
> }
> ```

Doesn't work for me :-(

**Comment by ashwin-dongare** [comment]
> A dirty fix is to just return getFilledEmailIntent(params) in getDraft(), but it works.
> 
> `Impl.java`
> 
> ```
> Intent getDraft (JSONObject params) {
>    return getFilledEmailIntent(params);
> }
> ```
Thanks
Works pretty well

**Comment by vLorente** [comment]
Thanks a lot @Melf11 ! Your fix save my life!

**Comment by PetePrattis** [comment]
@Melf11 's fix and some other fixes that I tried, resulted in Android 11 successfully opening a draft email after prompting all possible apps, but any attachments failed to attach. This small change in the `getDraft()` made it possible to show the correct apps in prompt and to successfully attach files. 
The change: 
`return Intent.createChooser(draft, header)` 
instead of 
`return Intent.createChooser(targets.remove(0), header)`  
Not sure what possible side effects there may be, but I tested it on Android 11 & 10 target sdk 30.

```
Intent getDraft (JSONObject params) {
        Intent draft  = getFilledEmailIntent(params);
        String app    = params.optString("app", MAILTO_SCHEME);
        String header = params.optString("chooserHeader", "Open with");

        if (!app.equals(MAILTO_SCHEME) && isAppInstalled(app)) {
            return draft.setPackage(app);
        }

        List<Intent> targets = new ArrayList<>();

        for (String clientId : getEmailClientIds()) {
            Intent target = (Intent) draft.clone();
            targets.add(target.setPackage(clientId));
        }

        return Intent.createChooser(draft, header)
                .putExtra(EXTRA_INITIAL_INTENTS, targets.toArray(new Parcelable[0]));
    }
```

**Comment by 188599** [comment]
> The issue is Android 11 blocking `queryIntentActivities()` I've made PR #368 to fix the issue. I only have limit range of devices for testing.
> 
> Try it, and comment if it doesn't work for any devices

I tried on our app and I couldn't get it to work, not sure I missed something.

Removed the old plugin and installed it again using cordova's 
```cordova plugin add https://github.com/ebhsgit/cordova-plugin-email-composer#pr-Fix_361-Android_11_support``` 

Checked the `plugin.xml` and it seems to be the correct one with the fix. Installed on an Android 11 device and it did not work. 

Already removed the entire platform and added it back again, nothing changes. If I missed anything, please let me know. Thanks in advance.

**Comment by ebhsgit** [comment]
@188599 

Can you check the `manifest.xml` to see it has the `queries` tag

```
<queries>
        <intent>
                <action android:name="android.intent.action.SENDTO" />
                <data android:scheme="mailto" />
            </intent>
</queries>
```

If not, then you have are using the fix version

**Comment by 188599** [comment]
@ebhsgit I don't see any a `manifest.xml` file anywere within the build, only the  `AndroidManifest.xml` and that one does not have the `queries` tag at all.

Do you use cordova as well? If you do, would you mind walking me through the steps you took to make this work? I'm certain I have the right plugin, because like I said the `plugins\cordova-plugin-email-composer\plugin.xml` does have the changes made by you, so it's something wrong in the build process that's not generating the proper tags in the xml file.

**Comment by jfoclpf** [comment]
Anyone has more feedback with the PR #368? 

Does it work stably on Android 11, with Chinese smartphones (Xiaomi, for example)?

Do the attachments work OK?
Does it pop up only email Apps?

@PetePrattis @ebhsgit @maxzirilli @niclaforge 
Which PR are you using in your projects in production?
