### ISSUE TITLE
Failed to build in ionic project

### ISSUE THREAD

**Issue by Epameinondas-Theodoropoulos** [katzer/cordova-plugin-email-composer#367]
\android\capacitor-cordova-android-plugins\src\main\java\de\appplant\cordova\emailcomposer\Provider.java:22: error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;
                                 ^

**Comment by jfoclpf** [comment]
@Epameinondas-Theodoropoulos does this problem still applies?
May I close this issue?

**Comment by jjfleet** [comment]
I have the same issue when builidng with command:

 ionic cordova build android -c=testing --release
 
 I am trying to use github actions. I've added the  3 commands(npm install jetifier, npx jetify, npx cap sync android) but it appears that my android folder is created in platforms/android:

![image](https://user-images.githubusercontent.com/41312161/142795128-af01d790-2bd6-465f-81c8-33e193a73928.png)

and my github action fails here:

![image](https://user-images.githubusercontent.com/41312161/142795224-ab90c06b-5b61-4988-8c26-0853e1b0b48b.png)

Any direction would really be appreciated on this. :) thanks

**Comment by jjfleet** [comment]
Nevermind, I got it going in Github Actions by removing the npx cap sync android step:

![image](https://user-images.githubusercontent.com/41312161/142798596-c4965690-740b-44d2-899d-a442c3266f21.png)

Hope this can be of use for anyone else coming across similar issues.

**Comment by jfoclpf** [comment]
Thank you for the feedback 

This is related with Android X and I hope PR #364 will solve this issue
