### ISSUE TITLE
On Android 11, emailComposer.open() do nothing nor call error 

### ISSUE THREAD

**Issue by catapulte2** [katzer/cordova-plugin-email-composer#371]
Hi, 
Thanks for your job.
It works perfectly on previous versions of Android but for information on Android 11, emailcomposer.open(email) do nothing.
It don't call .then nor error or catch functions call.
For moment I bypass this like this :

var ok : boolean = false;
this.emailComposer.open(email).then(result=>{      
     // Call on all release before Android 11
      ok = true;
    },e=>{
      //never call if android 11
    }).catch(e=>{
      //never call if android 11
    })
setTimeout(() => {
      if(!ok){ 
          //my call to Window.open with mailto function for android 11 devices
      }
 },3000); 

If you want me to make tests modifications on my code, your welcome.

Best regards, 

Eric

**Comment by jfoclpf** [comment]
The callback has no error parameter and the `open` method does not return any Promise, the docs are clear on that

```js
cordova.plugins.email.open({
    from:       String, // sending email account (iOS only)
    to:          Array, // email addresses for TO field
    cc:          Array, // email addresses for CC field
    bcc:         Array, // email addresses for BCC field
    attachments: Array, // file paths or base64 data streams
    subject:    String, // subject of the email
    body:       String, // email body
    isHtml:    Boolean  // indicats if the body is HTML or plain text (primarily iOS)
}, () => {
  console.log('Finished')
})
```

**Comment by Topiya** [comment]
@catapulte2 Did you find any solution yet?
I am facing a same issue.

**Comment by jfoclpf** [comment]
@Topiya did you try the code I posted here in the thread?


With me it works on Android 11

**Comment by catapulte2** [comment]
Hi Topiya,
We finally stop using Ionic and Cordova because we spent too much time searching for stability bugs.
I don't think it come from the Cordova plugin itself but from all the compile integration wich make more and more it's live alone. Sometime plugins work, sometime not... Nobody know why. ;-(
Regards,

**Comment by Topiya** [comment]
> The callback has no error parameter and the `open` method does not return any Promise, the docs are clear on that
> 
> ```js
> cordova.plugins.email.open({
>     from:       String, // sending email account (iOS only)
>     to:          Array, // email addresses for TO field
>     cc:          Array, // email addresses for CC field
>     bcc:         Array, // email addresses for BCC field
>     attachments: Array, // file paths or base64 data streams
>     subject:    String, // subject of the email
>     body:       String, // email body
>     isHtml:    Boolean  // indicats if the body is HTML or plain text (primarily iOS)
> }, () => {
>   console.log('Finished')
> })
> ```

@jfoclpf  I am getting below error while using above code.
`ERROR TypeError: Cannot read property 'email' of undefined`

**Comment by jfoclpf** [comment]
@Topiya as @catapulte2 referred you have a problem with installation, just check on the console the result of `typeof cordova.plugins.email`. It should be a function.

**Comment by Topiya** [comment]
Thank you. I have re-added android platform.
Now error is gone but main issue still persist, App crashes on `cordova.plugins.email.open` function call.

**Comment by jfoclpf** [comment]
@Topiya what exact error is shown on console.log ?

when you type in console dev tools `typeof cordova.plugins.email` and `typeof cordova.plugins.email.open` what do you see?
