### ISSUE TITLE
package androidx.core.content does not exist Android

### ISSUE THREAD

**Issue by ludonoel1** [katzer/cordova-plugin-email-composer#378]
Hello,
With my capacitorionic app, I have installed email-composer but when I try to build for android, I have this error:
package: androidx.core.content does not exist.

I have tried to add library in Android Studio but doesn't work.

Do you have an idea please ?!

Thanks

**Comment by jfoclpf** [comment]
you have to install the androidx adapter

```
ionic cordova plugin add cordova-plugin-androidx-adapter
```

**Comment by jfoclpf** [comment]
which one?
