### ISSUE TITLE
App getting crash as getEmailClientIds() return zero

### ISSUE THREAD

**Issue by ncomo11** [katzer/cordova-plugin-email-composer#382]
Hi!
In android 13 app getting crash when called email plugin's open function. On debugging it is due to 'getEmailClientIds()' returning 0 and in turn 'targets.remove(0), header' gives exception as targets ha nothing to remove.
This all happen inside 'getDraft' method of Impl.java files/class.

Thanks,
Praveen
![image](https://github.com/katzer/cordova-plugin-email-composer/assets/859748/7f6af74b-f62f-4133-af9a-98116b2dbcad)
![image](https://github.com/katzer/cordova-plugin-email-composer/assets/859748/ee104f43-137b-4098-8c9e-df3f26ddc21b)

**Comment by jfoclpf** [comment]
and BTW, I am using this plugin on Android 13 with no issues at all, it works nice, here where I call the open method
https://github.com/jfoclpf/form-for-parking-violation/blob/master/www/js/main.js#L279

are you using in any particular context?

**Comment by ncomo11** [comment]
@jfoclpf I am using in same way but its crashing for me consistently. Tested on android 13 device and android 12 emulator its crashing on both.

**Comment by ncomo11** [comment]
@jfoclpf Thanks with the latest version issue is fixed. 
Thanks,

**Comment by jfoclpf** [comment]
> @jfoclpf Thanks with the latest version issue is fixed. Thanks,

what do you mean? We did not change anything
