### ISSUE TITLE
plugin throws errors on cordova/phongap 3.1

### ISSUE THREAD

**Issue by manorius** [katzer/cordova-plugin-email-composer#4]
Hi,

I've installed the plugin on cordova 3.1 and I'm getting the following 2 errors whenever I'm trying to use it.

When I load the app to my android device:
11-08 15:47:25.689: E/Web Console(29177): Uncaught ReferenceError: module is not defined at file:///android_asset/www/js/email_composer.js:51

When I invoke window.plugin.email.open
11-08 15:54:07.348: E/Web Console(29177): Uncaught TypeError: Converting circular structure to JSON at file:///android_asset/www/cordova.js:901

Any help is highly appreciated.
Thanks

**Comment by jamesone** [comment]
I had this same problem. All I had to do was include the following in my root www index.html: 
`<script type="text/javascript" charset="utf-8" src="cordova.js"></script>  
<script type="text/javascript" charset="utf-8" src="cordova_plugins.js"></script>  `

Now you may not have these files in your ROOT WWW, but when you build the application, node will attach the correct files to the platform your using.
