### ISSUE TITLE
Crash after email.open.

### ISSUE THREAD

**Issue by Sorcim** [katzer/cordova-plugin-email-composer#59]
Hi, 

when i open a email, my simulator crash with this error : 

bool _WebTryThreadLock(bool), 0x7fcf5307f280: Tried to obtain the web lock from a thread other than the main thread or the web thread. This may be a result of calling to UIKit from a secondary thread. Crashing now...
1   0x108223f5b WebThreadLock
2   0x1029a3db4 -[UIWebView stringByEvaluatingJavaScriptFromString:]
3   0x10210c689 -[CDVViewController shouldAutorotateToInterfaceOrientation:]
4   0x10211c8f9 -[MainViewController shouldAutorotateToInterfaceOrientation:]
5   0x10210c79d -[CDVViewController supportedInterfaceOrientations]
6   0x10287bd82 -[UIViewController __supportedInterfaceOrientations]
7   0x1028715c3 -[UIViewController _preferredInterfaceOrientationGivenStatusBarAndDeviceAndOrientation:]
8   0x102e05092 -[_UIFullscreenPresentationController _adjustOrientationIfNecessaryInWindow:forViewController:preservingViewController:]
9   0x102844d4f -[UIPresentationController _dismissWithAnimationController:interactionController:target:didEndSelector:]
10  0x102877a3b -[UIViewController _dismissViewControllerWithAnimationController:interactionController:completion:]
11  0x1028776b9 -[UIViewController _dismissViewControllerWithTransition:from:completion:]
12  0x102876ed0 -[UIViewController dismissViewControllerWithTransition:completion:]
13  0x102876d6a -[UIViewController dismissViewControllerWithTransition:completion:]
14  0x102878ef4 -[UIViewController dismissViewControllerAnimated:completion:]
15  0x1021467ba -[APPEmailComposer mailComposeController:didFinishWithResult:error:]
16  0x1042555e3 -[MFMailComposeInternalViewController _finishServiceViewControllerRequestWithSuccess:]
17  0x104b2402c __NSXPCCONNECTION_IS_CALLING_OUT_TO_ERROR_BLOCK__
18  0x104b24f19 __97-[NSXPCConnection _sendInvocation:proxyNumber:remoteInterface:withErrorHandler:timeout:userInfo:]_block_invoke300
19  0x1058333d2 _xpc_connection_reply_callout
20  0x10582ba7a _xpc_connection_call_reply
21  0x1055337f4 _dispatch_client_callout
22  0x10551bbf4 _dispatch_queue_drain
23  0x10551b506 _dispatch_queue_invoke
24  0x10551dff7 _dispatch_root_queue_drain
25  0x10551f63c _dispatch_worker_thread2
26  0x1058c9ef8 _pthread_wqthread
27  0x1058ccfb9 start_wqthread

**Comment by privetr** [comment]
Sorry, but the issue still exists on an Ipad Air 2 with iOS 8 (Not an emulator, but a real device).
Anything to fix it ?

**Comment by privetr** [comment]
And with iOS 9 I also have the problem. I use it with Ionic Framework, I don't know if it can comes from here... On Android it works fine.

**Comment by jkearse3** [comment]
To second @privetr, I'm working on a cordova application using this plugin via ngCordova, and when building the iOS version, I get this same error.

**Comment by johnnypark** [comment]
Same problem here with a iOS9 iPhone6...

**Comment by privetr** [comment]
It seems that no more support  is done on this plugin. So bad because I can't find another one which send emails...
