### ISSUE TITLE
It is crashing Gmail app

### ISSUE THREAD

**Issue by Kushi171987** [katzer/cordova-plugin-email-composer#62]
Hi,

I used this plugin in my Android phonegap application.
When I tried to add the attachment and sending the mail each time it is crashing the Gmail app and showing " Unfortunately Gmail has stopped" . I checked that file has data also.
But didn't find the solution.
Can any one help me please..
Thanks in advance

**Comment by divyenduz** [comment]
I am facing similar issue :(
