### ISSUE TITLE
No response from plugin

### ISSUE THREAD

**Issue by Kronkorken** [katzer/cordova-plugin-email-composer#68]
Used to work fine. But now with iOS 8.1 (not 8.0.1) it does not work anymore. I tried the plugin with version 8.0.1 and 8.0.2dev. Installed it via CLI

All files are included and linked inside config.xml and cordova_plugins.js. I even created blank projects to try out the plugin. It does not respond to cordova.plugins.email.open();

**Comment by dantaylor** [comment]
thank you for posting the answer to that. It helped me a bunch :-)
