### ISSUE TITLE
Windows support not working - no Windows.ApplicationModel.Email on Windows 8 / Windows 8.1 Desktop clients

### ISSUE THREAD

**Issue by mobidev111** [katzer/cordova-plugin-email-composer#73]
Version: Cordova 4.0.0

The current email composer windows implementation can not work on Windows 8.1, as Windows.ApplicationModel.Email is not supported on this platform: 

Fails with undefined:
```javascript
 var mail = new Windows.ApplicationModel.Email.EmailMessage();
```

Email Documentation:
http://msdn.microsoft.com/en-us/library/windows/apps/windows.applicationmodel.email.aspx
Minimum supported client: None supported

Compare this to Appointments:
http://msdn.microsoft.com/en-us/library/windows/apps/windows.applicationmodel.appointments.aspx
Minimum supported client: Windows 8.1

**Comment by katzer** [comment]
@hdramos, thats not possible because attachments are binary data.

**Comment by hdramos** [comment]
@katzer 

I don't understand your comment above: "The windows platform right now is intended to support WP 8.1"

The docs state Windows is supported as well as WP8.0 and 8.1, what functionality is supported in Windows?

**Comment by katzer** [comment]
cordova's windows platform targets Windows 8.1 and Windows Phone 8.1. But currently the plugin supports only Windows Phone 8.1

**Comment by hdramos** [comment]
The docs list both Windows and WP as supported:

   WP 8.0 and WP 8.1 Silverlight
   Windows

What does it mean by supports "Windows"?

**Comment by katzer** [comment]
`windows` refers to the name of the cordova platform. If you want to use the plugin on Windows Phone 8.1, then add the windows platform and add the plugin. But the plugin will not work on Windows 8.1 OS.
