### ISSUE TITLE
Not working in Android 5

### ISSUE THREAD

**Issue by asierdelpozo** [katzer/cordova-plugin-email-composer#77]
In a Nexus 6 device (Android 5) I tested the app with both

window.plugin.email.isServiceAvailable(function(isAvailable) {
alert(isAvailable);
});
and
cordova.plugins.email.isAvailable(function(isAvailable) { 
alert(isAvailable);
});

the first alert shows the value false, and the second alert is never reached. But if I ignore the value and execute window.plugin.email.open, it works fine.

From the documentation I understood that the second option would be the available one, but it looks like it is the first one; anyway, the call returns not available... any ideas?

**Comment by regnete** [comment]
We are facing the same issue under Android 5.0.1 running on Nexus7.
window.plugin.email.isServiceAvailable always delivers false.

**Comment by katzer** [comment]
`isAvailable` returns _false_ if there is no email app installed. It works under Android 5 on Nexus 5.

**Comment by wangkang89** [comment]
Hi there
I am testing your plugin on my Google Nexus 7.

cordova.plugins.email.isAvailable(function (isAvailable) {
              var email = {
                to: to,
                subject: 'Mermuring mail',
                body: 'How are you? Nice greetings from Mermuring'
              };
              cordova.plugins.email.open(email);
            });
The isAvailable() function is working on this device, but email.open is not working properly.

The empty modal with "No apps can perform this action." caption, is opened.
Please let me know any solution for this.

Thanks and Regards
Wang

**Comment by donminos** [comment]
Hi i am testing the plugin en ios 10 and android 5.X and the window.plugin.email.isServiceAvailable function is always false

**Comment by Saviance** [comment]
Any update on this. I am facing the same issue. IsAvailable returns true but isServiceAvailable returns false.
