### ISSUE TITLE
iOS - 8.1.2 and 6.1.6 - service not available.(Question/Problem)

### ISSUE THREAD

**Issue by boh7978** [katzer/cordova-plugin-email-composer#81]
This plugin doesn't support ios 8.1.2 and 6.1.6???
Although i got a false, when I use the 'isAvailable' function.
I just wanna make sure this one.

**Comment by SubjectiveEffect** [comment]
I'm finding it doesn't work on iOS 8.1.2 as well.

**Comment by katzer** [comment]
It works with iOS 8.x (with a physical device!)

`isAvailable` returns false can have on of the following reasons:
- there is no emil account configured
- email support for the account is disabled
- older devices & OS versions do not support it, see [canSendMail](https://developer.apple.com/library/prerelease/ios/documentation/MessageUI/Reference/MFMailComposeViewController_class/index.html#//apple_ref/occ/clm/MFMailComposeViewController/canSendMail)
