### ISSUE TITLE
Callback can't differentiate success from failure

### ISSUE THREAD

**Issue by ptarjan** [katzer/cordova-plugin-email-composer#84]
Regardless of whether the user sends the email or not, callback is always called. Tested on IOS and Android.

According to my cursory googling, it seems impossible to differentiate on android, but on iOS you get a callback and can figure out if the message was sent. Can we get this passed up to javascript please?

**Comment by PKnittel** [comment]
To ensure same functionality on both platforms, we decided to not implement this feature only on ios.
