### ISSUE TITLE
Yahoo mail android app issue

### ISSUE THREAD

**Issue by vasnakos** [katzer/cordova-plugin-email-composer#89]
While gmail and other mail client apps work okay with this plugin, when I'm using Yahoo mail app on android the mail body doesn't seem to work with html tags and displays all mail body to one line.
For example if I use <br> to go to new line, yahoo app displays all mail body content to one line. This happens whatever tags I may use.

I'm using cordova 3.6.3 and email-composer 0.8.2.

Thanks in advance!

**Comment by PKnittel** [comment]
We aren´t able to offer a solution for this problem. Unfortunately, there is no accurately defined interface for Email-Applications on android.
