### ISSUE TITLE
Plugin failing on iOS 8+ but working on Android 5

### ISSUE THREAD

**Issue by SubjectiveEffect** [katzer/cordova-plugin-email-composer#92]
I get this error in XCode when I try to Archive too: 

    clang: error: no such file or directory: '/Users/SubjectiveEffect/myCards/platforms/ios/myAppName/Plugins/de.appplant.cordova.plugin.email-composer/APPEmailComposer.m'
    clang: error: no input files
    Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

Any idea what is going on?

**Comment by katzer** [comment]
thats hard to analyze from remote. I am sure you have checked if the file is in place.

**Comment by SubjectiveEffect** [comment]
I found out what the issue is I think - it was an ionic ios platform problem, solved by removing and re-adding it.
