### ISSUE TITLE
app crash in android with this plugin.

### ISSUE THREAD

**Issue by seematalanki** [katzer/cordova-plugin-email-composer#93]
Android app crash with below error when we  have email compose plugin installed. Let us know if we need to do any project settings other than installing the plugin.

02-27 19:58:07.566: E/AndroidRuntime(22344): FATAL EXCEPTION: main
02-27 19:58:07.566: E/AndroidRuntime(22344): Process: com.apppoint.appsonmobilesuite, PID: 22344
02-27 19:58:07.566: E/AndroidRuntime(22344): java.lang.RuntimeException: Unable to get provider de.appplant.cordova.plugin.emailcomposer.AttachmentProvider: java.lang.ClassNotFoundException: Didn't find class "de.appplant.cordova.plugin.emailcomposer.AttachmentProvider" on path: DexPathList[[zip file "/data/app/com.apppoint.appsonmobilesuite-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.apppoint.appsonmobilesuite-1, /vendor/lib, /system/lib]]
02-27 19:58:07.566: E/AndroidRuntime(22344): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5256)
02-27 19:58:07.566: E/AndroidRuntime(22344): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4847)
02-27 19:58:07.566: E/AndroidRuntime(22344): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4730)
02-27 19:58:07.566: E/AndroidRuntime(22344): 	at android.app.ActivityThread.access$1600(ActivityThread.java:172)
02-27 19:58:07.566: E/AndroidRuntime(22344): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
02-27 19:58:07.566: E/AndroidRuntime(22344): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-27 19:58:07.566: E/AndroidRuntime(22344): 	at android.os.Looper.loop(Looper.java:146)
02-27 19:58:07.566: E/AndroidRuntime(22344): 	at android.app.ActivityThread.main(ActivityThread.java:5653)
02-27 19:58:07.566: E/AndroidRuntime(22344): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-27 19:58:07.566: E/AndroidRuntime(22344): 	at java.lang.reflect.Method.invoke(Method.java:515)
02-27 19:58:07.566: E/AndroidRuntime(22344): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
02-27 19:58:07.566: E/AndroidRuntime(22344): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
02-27 19:58:07.566: E/AndroidRuntime(22344): 	at dalvik.system.NativeStart.main(Native Method)
02-27 19:58:07.566: E/AndroidRuntime(22344): Caused by: java.lang.ClassNotFoundException: Didn't find class "de.appplant.cordova.plugin.emailcomposer.AttachmentProvider" on path: DexPathList[[zip file "/data/app/com.apppoint.appsonmobilesuite-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.apppoint.appsonmobilesuite-1, /vendor/lib, /system/lib]]
02-27 19:58:07.566: E/AndroidRuntime(22344): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
02-27 19:58:07.566: E/AndroidRuntime(22344): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
02-27 19:58:07.566: E/AndroidRuntime(22344): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
02-27 19:58:07.566: E/AndroidRuntime(22344): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5241)

**Comment by katzer** [comment]
hi @seematalanki,
I will release v0.8.2 soon which does not make use of providers anymore.

**Comment by vinaybr** [comment]
Hi @katzer,

I am facing the same problem, waiting for the newer version.

**Comment by katzer** [comment]
Version 0.8.2 has been released and will also be published on PGB. Thanks!
