### ISSUE TITLE
How to check what email app to use?

### ISSUE THREAD

**Issue by mladenp** [katzer/cordova-plugin-email-composer#95]
I don't know what **isAvailable** checks for, but i would like to use default email app to send email. Is there a way to check what email app is default one? 
I know there is a way to check which packages are installed on android, but manually checking packages is much of a hassle for this simple thing.

**Comment by katzer** [comment]
@mladenp, `isAvailable` returns _false_ if there is no email app installed on the device.

If there are multiple email apps available, a chooser will pop-up. Otherwise its possible to specify the email app: https://github.com/katzer/cordova-plugin-email-composer#specify-email-app

**Comment by mladenp** [comment]
Yeah i know that, but popup/email chooser has a lot of junk in it that's not email client, like "beam it", "share via lan" ...
And if i specify gmail app and user doesn't have one then email will fail.

**Comment by Hirbod** [comment]
If you know the url scheme of gmail app, you could use the app availability plugin to check for gmail before you try to open it

https://github.com/ohh2ahh/AppAvailability/blob/master/README.md

**Comment by Hirbod** [comment]
The scheme is googlemail://

**Comment by mladenp** [comment]
That's what i was thinking of doing, but there are a lot of different email clients that people can use, so i'll probably have to think of some other full proof option to send email.

**Comment by Hirbod** [comment]
I guess the best option should be to leave the decision at the users side. Even if they have multiple mail clients, you'll probably never be able to determine the users favorite one
