### ISSUE TITLE
Base 64 attachments doesn't seems to work.

### ISSUE THREAD

**Issue by martin-robillard** [katzer/cordova-plugin-email-composer#96]
Hi, i'm probably doing something wrong here... Here is my call:
window.cordova.plugins.email.open({
  to:      '',
  subject: 'Zylkene tests',
  body:    'Please download the csv file',
  attachments: 'data:image/png;base64,AAAFBfj42Pj4'
});

I also trying to pass an array for the attachments.

The email is sending but the attachement is a txt file. Ultimately I'll be sending a .csv. I'm under ios 8.1 and building with cordova 4.2. Maybe its my cordova version that is too cutting edge? Thanks for your time.

Martin

**Comment by martin-robillard** [comment]
I fucked up...  Here is my final line:
attachments: "base64:tests.csv//" + csv

It work properly, sorry for the trouble :)

**Comment by adamduren** [comment]
I'm curious, what is the above format called? I thought it was a `data URI` at first as the author originally posted but it's something similar but different.
