### ISSUE TITLE
Couldn't send attachment

### ISSUE THREAD

**Issue by cicka127** [katzer/cordova-plugin-email-composer#97]
Base64 attachments don't work on android

**Comment by modess** [comment]
I had the same issue after updating to the latest version (0.8.2). Before I made it work with a workaround.

So first install 0.8.1:

    cordova plugin add de.appplant.cordova.plugin.email-composer@0.8.1

Then modify your base64-string and attach it like this:

    var filename         = 'some_filename.pdf';
    var attachmentBase64 = ''; // This should be your base64-string

    var base64parts = attachmentBase64.split(',');
    base64parts[0] = "base64:" + escape(filename) + "//";
    var compatibleAttachment =  base64parts.join("");

    window.plugin.email.open({
        attachments: [compatibleAttachment],
        [...]
    });

And it should work on both iOS and Android.

**Comment by maersu** [comment]
same here.

@modess, 0.8.1 doesn't not work for me either :(

**Comment by isaaccarrington** [comment]
I am having the same difficulty. I tried your method but it still has not worked.

var base64parts = attachmentBase64.split(','); <--- I thought base64 strings had no commas though?

**Comment by maersu** [comment]
@isaaccarrington and @cicka127:  fyi

I was not able to get this plugin to work with attachments. But I found another plugin that works on android and ios:
https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin

````
window.plugins.socialsharing.shareViaEmail(
   'Message', 
   'Subject', 
   ['mail@to.com'], null, null, 
   [''data:text/vcf;base64,QkVHSU46VkNBUkQKRk....]);
```

**Comment by isaaccarrington** [comment]
@maersu Thanks for the link. I couldn't get it going after a few attempts so gave up in favour of this method:
I needed to send a CSV file so instead I just sent the data in the body of the email and made an online tool to create the file.from the data.

**Comment by aherold** [comment]
@isaaccarrington 
I've been using this plugin to attach a csv file to an email for the past year, however, the isAvailable() function does not work on Android 5 and version 8.2 of this plugin removes new lines from the body of the email. I'm using version 8.1 and have removed my calls to isAvailable(). I may check out the Social Sharing plugin as well if this one continues to have issues.

Here is the code I'm using:
```javascript
    this.send = function() {
		window.requestFileSystem(LocalFileSystem.PERSISTENT, 0 /*unknown size*/, onInitFs, errorHandler);
    };
    
    function onInitFs(fs) {
  	  // Create a directory for this app at the filesystem root
  	  fs.root.getDirectory("badgescan", {create: true}, onDirSuccess, onDirFail);
  	}

    function onDirSuccess(dirEntry) {
    	// Create a file to save our contacts to
		  dirEntry.getFile("badgerscan.csv", {create: true, exclusive: false}, onFileSuccess, errorHandler);
    };
    
    function onFileSuccess(fileEntry) {
		// Create a FileWriter object for our FileEntry.
		fileEntry.createWriter(function(fileWriter) {

			fileWriter.onwriteend = function(e) {
			    console.log('Done writing file badgerscan.csv:');		        
			    var pathToFile = fileEntry.toURL();
			    
			    // iOS needs a relative path
		    	if ( window.device.platform === 'iOS' ) {        
		    		pathToFile = pathToFile.replace("file://", "");
		    	}
		    	
			    // Attach the file URL to an email
			    window.plugin.email.open({
				    subject: 'Contacts',
				    body:    'Body goes here.',
				    attachments: [pathToFile]
				});
			};
			
			fileWriter.onerror = function(e) {
			    console.log('Write failed: ' + e.toString());
			    //alert('Write failed: ' + e.toString());
			    alert('Unable to create export file.');
			};
			  
			// Create the guts of the csv file
			var contactsCSV = buildContactsCSV();
			
			// Create a new Blob and write it out.
			var blob = new Blob([contactsCSV], {type: 'text/plain'});
			fileWriter.write(blob);
		      
		}, errorHandler);
    };

    function onDirFail(error) {
        //Error while creating directory
        //alert("Unable to create new directory: " + error.code);
    	alert('Unable to create export file.');
    };
    
    function errorHandler(e) {
    	  console.log('Error: ' + e.toString);
    	  //alert('Error: ' + e.toString);
    	  alert('Unable to create export file.');
    };  
    
    function emailCB(result) {
    	  console.log('email composer returned: ' + result);
    };

    function buildContactsCSV() {
    	var str = '' //return string    		
	return str;
    };
```

**Comment by justingish** [comment]
Thanks @modess, your solution worked for me!

**Comment by PKnittel** [comment]
We tested base64 files on android 5 and 4.1 and it worked. You just have to take care of files with the same name. Base64, Resource and Asset attachments are stored in the same folder now, so identically named files effect errors.
This issue will be fixed with the next major-release. 

Take a look at the examplebranch for more information about how to attach files.

Please tell us whether that solved your problem or not.

Greatings Philipp

**Comment by jdnichollsc** [comment]
+1 in Android 4.2.2

**Comment by manojrejinthala** [comment]
i have issue with ios device i gave the path with file name but attachment missing i used to create file using ngcordova file .i stored the file documents of ios device .thanks in advance

**Comment by hyderlyger** [comment]
I had issue with Base64 image attachments in android. I was seeing broken attachment file like: "filename.*;charset=utf-8". I fixed it by following: (I hope it helps someone else too)

`if(this.platform.is("android")) //Android image attachment fix
        if(attachments_base64)
          for(var i = 0; i< attachments_base64.length; i++)
            attachments_base64[i] = attachments_base64[i].replace('*;charset=utf-8','jpeg')`
