### ISSUE TITLE
No Error/Exception Handling if no E-mail Client is configured 

### ISSUE THREAD

**Issue by harshjain17** [katzer/cordova-plugin-email-composer#99]
I am using this plugin on iOS 8.2  and by default there is no email client configured on the device.  The plugin does not throws any warning or error call back to capture this exception.

**Comment by yogesh2022** [comment]
Add this code inside open function and you will be able to get an alert message if no email client is configured.

if (![MFMailComposeViewController canSendMail]) {
        UIAlertView *alert2 = [[UIAlertView alloc] initWithTitle:@"No Email Client Found"
                                                         message:@"Configure email client on device."
                                                        delegate:nil
                                               cancelButtonTitle:@"OK"
                                               otherButtonTitles:nil];
        [alert2 show];
        return;
    }

**Comment by katzer** [comment]
You can make use of `isAvailable()`.
